<?php

use Illuminate\Database\Seeder;

class DrugsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
  DB::table('tbl_principi_attivi')->insert([
  //    ['id_principio_attivo' => 'a','descrizione' => 'Paracetamolo','id_cas' => ''],
      ['id_principio_attivo' => 'A01AB08','descrizione' => 'Neomicina','id_cas' => 'cf117'],
      ['id_principio_attivo' => 'A01AD01','descrizione' => 'Adrenalina','id_cas' => 'cf117'],
      ['id_principio_attivo' => 'A01AD05','descrizione' => 'Aspirina','id_cas' => 'cf117'],
      ['id_principio_attivo' => 'A02AH01','descrizione' => 'Bicarbonato Di Sodio','id_cas' => 'cf044'],
      ['id_principio_attivo' => 'A02BA01','descrizione' => 'Cimetidina','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BA02','descrizione' => 'Ranitidina','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BA04','descrizione' => 'Nizatidina','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BC01','descrizione' => 'Omeprazole','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BC02','descrizione' => 'Pantoprazole','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BC03','descrizione' => 'Lansoprazole','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BC05','descrizione' => 'Esomeprazole','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A02BX05','descrizione' => 'Bismuto Subcitrato','id_cas' => 'cf091'],
      ['id_principio_attivo' => 'A03AC05','descrizione' => 'Tiropramide','id_cas' => 'cf089'],
      ['id_principio_attivo' => 'A03AE02','descrizione' => 'Tegaserod','id_cas' => 'cf089'],
      ['id_principio_attivo' => 'A03BA01','descrizione' => 'Atropina','id_cas' => 'cf066'],
      ['id_principio_attivo' => 'A03FA01','descrizione' => 'Metoclopramide','id_cas' => 'cf118'],
      ['id_principio_attivo' => 'A03FA02','descrizione' => 'Cisapride','id_cas' => 'cf118'],
      ['id_principio_attivo' => 'A03FA03','descrizione' => 'Domperidone','id_cas' => 'cf118'],
      ['id_principio_attivo' => 'A04AA02','descrizione' => 'Granisetron','id_cas' => 'cf052'],
      ['id_principio_attivo' => 'A04AA05','descrizione' => 'Palonosetron','id_cas' => 'cf052'],
      ['id_principio_attivo' => 'A04AA55','descrizione' => 'Palonosetron, Combinations','id_cas' => 'cf052'],
      ['id_principio_attivo' => 'A04AD12','descrizione' => 'Aprepitant','id_cas' => 'cf052'],
      ['id_principio_attivo' => 'A05AA03','descrizione' => 'Cholic Acid','id_cas' => 'cf131'],
      ['id_principio_attivo' => 'A06AG04','descrizione' => 'Glicerolo','id_cas' => 'cf102'],
      ['id_principio_attivo' => 'A06AH01','descrizione' => 'Methylnaltrexone Bromide','id_cas' => 'cf102'],
      ['id_principio_attivo' => 'A06AH03','descrizione' => 'Naloxegol','id_cas' => 'cf102'],
      ['id_principio_attivo' => 'A06AX04','descrizione' => 'Linaclotide','id_cas' => 'cf102'],
      ['id_principio_attivo' => 'A06AX05','descrizione' => 'Prucalopride','id_cas' => 'cf102'],
      ['id_principio_attivo' => 'A07AA11','descrizione' => 'Rifaximina','id_cas' => 'cf058'],
      ['id_principio_attivo' => 'A07AA12','descrizione' => 'Fidaxomicin','id_cas' => 'cf058'],
      ['id_principio_attivo' => 'A07DA03','descrizione' => 'Loperamide','id_cas' => 'cf062'],
      ['id_principio_attivo' => 'A07EA06','descrizione' => 'Budesonide','id_cas' => 'cf088'],
      ['id_principio_attivo' => 'A07EA07','descrizione' => 'Beclometasone','id_cas' => 'cf088'],
      ['id_principio_attivo' => 'A08AA01','descrizione' => 'Phentermine','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA02','descrizione' => 'Fenfluramine','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA03','descrizione' => 'Amfepramone','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA04','descrizione' => 'Dexfenfluramine','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA05','descrizione' => 'Mazindol','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA08','descrizione' => 'Clobenzorex','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA09','descrizione' => 'Mefenorex','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA10','descrizione' => 'Sibutramine','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AA62','descrizione' => 'Bupropion And Naltrexone','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AB01','descrizione' => 'Orlistat','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A08AX01','descrizione' => 'Rimonabant','id_cas' => 'cf112'],
      ['id_principio_attivo' => 'A09AA02','descrizione' => 'Enzimi Pancreatici','id_cas' => 'cf075'],
      ['id_principio_attivo' => 'A10AB01','descrizione' => 'Insulin Human','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AB04','descrizione' => 'Insulin Lispro','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AB05','descrizione' => 'Insulin Aspart','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AB06','descrizione' => 'Insulin Glulisine','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AC01','descrizione' => 'Insulin Human','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AD01','descrizione' => 'Insulin Human','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AD05','descrizione' => 'Insulin Aspart','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AD06','descrizione' => 'Insulin Degludec And Insulin Aspart','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AE04','descrizione' => 'Insulin Glargine','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AE05','descrizione' => 'Insulin Detemir','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AE06','descrizione' => 'Insulin Degludec','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AE56','descrizione' => 'Insulin Degludec And Liraglutide','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10AF01','descrizione' => 'Insulin Human','id_cas' => 'cf099'],
      ['id_principio_attivo' => 'A10BA02','descrizione' => 'Metformin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BB12','descrizione' => 'Glimepiride','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD03','descrizione' => 'Metformin And Rosiglitazone','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD04','descrizione' => 'Glimepiride And Rosiglitazone','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD05','descrizione' => 'Metformin And Pioglitazone','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD06','descrizione' => 'Glimepiride And Pioglitazone','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD07','descrizione' => 'Metformin And Sitagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD08','descrizione' => 'Metformin And Vildagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD09','descrizione' => 'Pioglitazone And Alogliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD10','descrizione' => 'Metformin And Saxagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD11','descrizione' => 'Metformin And Linagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD13','descrizione' => 'Metformin And Alogliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD15','descrizione' => 'Metformin And Dapagliflozin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD16','descrizione' => 'Metformin And Canagliflozin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BD20','descrizione' => 'Metformin And Empagliflozin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BG02','descrizione' => 'Rosiglitazone','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BG03','descrizione' => 'Pioglitazone','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BH01','descrizione' => 'Sitagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BH02','descrizione' => 'Vildagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BH03','descrizione' => 'Saxagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BH04','descrizione' => 'Alogliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BH05','descrizione' => 'Linagliptin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX02','descrizione' => 'Repaglinide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX03','descrizione' => 'Nateglinide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX04','descrizione' => 'Exenatide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX06','descrizione' => 'Benfluorex','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX07','descrizione' => 'Liraglutide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX09','descrizione' => 'Dapagliflozin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX10','descrizione' => 'Lixisenatide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX11','descrizione' => 'Canagliflozin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX12','descrizione' => 'Empagliflozin','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX13','descrizione' => 'Albiglutide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A10BX14','descrizione' => 'Dulaglutide','id_cas' => 'cf087'],
      ['id_principio_attivo' => 'A11CA01','descrizione' => 'Tiropramide','id_cas' => 'cf140'],
      ['id_principio_attivo' => 'A11CC04','descrizione' => 'Calcitriolo','id_cas' => 'cf140'],
      ['id_principio_attivo' => 'A11HA03','descrizione' => 'Riboflavina','id_cas' => 'cf033'],
      ['id_principio_attivo' => 'A11HA08','descrizione' => 'Tocofersolan','id_cas' => 'cf033'],
      ['id_principio_attivo' => 'A16AA04','descrizione' => 'Mercaptamine','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AA05','descrizione' => 'Carglumic Acid','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AA06','descrizione' => 'Betaine','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB02','descrizione' => 'Imiglucerase','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB03','descrizione' => 'Agalsidase Alfa','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB04','descrizione' => 'Agalsidase Beta','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB05','descrizione' => 'Laronidase','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB07','descrizione' => 'Alglucosidase Alfa','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB08','descrizione' => 'Galsulfase','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB09','descrizione' => 'Idursulfase','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB10','descrizione' => 'Velaglucerase Alfa','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB11','descrizione' => 'Taliglucerase Alfa','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AB12','descrizione' => 'Elosulfase Alfa','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX03','descrizione' => 'Sodium Phenylbutyrate','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX04','descrizione' => 'Nitisinone','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX05','descrizione' => 'Zinc Acetate','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX06','descrizione' => 'Miglustat','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX07','descrizione' => 'Sapropterin','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX08','descrizione' => 'Teduglutide','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX09','descrizione' => 'Glycerol Phenylbutyrate','id_cas' => 'cf036'],
      ['id_principio_attivo' => 'A16AX10','descrizione' => 'Eliglustat','id_cas' => 'cf036'],
  //    ['id_principio_attivo' => 'b','descrizione' => 'Fluimucil','id_cas' => ''],
      ['id_principio_attivo' => 'B01AA07','descrizione' => 'Acenocumarolo','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AB01','descrizione' => 'Eparina','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AB02','descrizione' => 'Antithrombin','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC04','descrizione' => 'Clopidogrel','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC09','descrizione' => 'Epoprostenol','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC11','descrizione' => 'Iloprost','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC16','descrizione' => 'Eptifibatide','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC17','descrizione' => 'Tirofiban','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC22','descrizione' => 'Prasugrel','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC24','descrizione' => 'Ticagrelor','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC25','descrizione' => 'Cangrelor','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC26','descrizione' => 'Vorapaxar','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC27','descrizione' => 'Selexipag','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AC30','descrizione' => 'Combinations','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AD02','descrizione' => 'Alteplase','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AD07','descrizione' => 'Reteplase','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AD08','descrizione' => 'Saruplase','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AD10','descrizione' => 'Drotrecogin Alfa Activated','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AD11','descrizione' => 'Tenecteplase','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AD12','descrizione' => 'Protein C','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AE01','descrizione' => 'Desirudin','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AE02','descrizione' => 'Lepirudin','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AE06','descrizione' => 'Bivalirudin','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AE07','descrizione' => 'Dabigatran Etexilate','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AF01','descrizione' => 'Rivaroxaban','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AF02','descrizione' => 'Apixaban','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AX01','descrizione' => 'Defibrotide','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B01AX05','descrizione' => 'Fondaparinux','id_cas' => 'cf083'],
      ['id_principio_attivo' => 'B02AA01','descrizione' => 'Aminocaproic Acid','id_cas' => 'cf054'],
      ['id_principio_attivo' => 'B02AA02','descrizione' => 'Tranexamic Acid','id_cas' => 'cf054'],
      ['id_principio_attivo' => 'B02AB01','descrizione' => 'Aprotinin','id_cas' => 'cf054'],
      ['id_principio_attivo' => 'B02AB02','descrizione' => 'Alfa1 Antitrypsin','id_cas' => 'cf054'],
      ['id_principio_attivo' => 'B02BA01','descrizione' => 'Fitomenadione','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BC30','descrizione' => 'Combinations','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD02','descrizione' => 'Coagulation Factor Viii','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD04','descrizione' => 'Coagulation Factor Ix','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD06','descrizione' => 'Von Willebrand Factor And Coagulation Factor Viii In Combination','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD08','descrizione' => 'Eptacog Alfa Activated','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD09','descrizione' => 'Nonacog Alfa','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD11','descrizione' => 'Catridecacog','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD13','descrizione' => 'Coagulation Factor X','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BD14','descrizione' => 'Susoctocog Alfa','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BX04','descrizione' => 'Romiplostim','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B02BX05','descrizione' => 'Eltrombopag','id_cas' => 'cf141'],
      ['id_principio_attivo' => 'B03AA01','descrizione' => 'Ferro Saccarato','id_cas' => 'cf111'],
      ['id_principio_attivo' => 'B03AA02','descrizione' => 'Ferro Fumarato','id_cas' => 'cf111'],
      ['id_principio_attivo' => 'B03AA03','descrizione' => 'Ferro Gluconato','id_cas' => 'cf111'],
      ['id_principio_attivo' => 'B03AA04','descrizione' => 'Ferro Carbonile','id_cas' => 'cf111'],
      ['id_principio_attivo' => 'B03AA07','descrizione' => 'Solfato Ferroso','id_cas' => 'cf111'],
      ['id_principio_attivo' => 'B03AB10','descrizione' => 'Ferric Maltol','id_cas' => 'cf111'],
      ['id_principio_attivo' => 'B03XA01','descrizione' => 'Erythropoietin','id_cas' => 'cf016'],
      ['id_principio_attivo' => 'B03XA02','descrizione' => 'Darbepoetin Alfa','id_cas' => 'cf016'],
      ['id_principio_attivo' => 'B03XA03','descrizione' => 'Methoxy Polyethylene Glycol-Epoetin Beta','id_cas' => 'cf016'],
      ['id_principio_attivo' => 'B06AC01','descrizione' => 'C1-Inhibitor, Plasma Derived','id_cas' => 'cf025'],
      ['id_principio_attivo' => 'B06AC04','descrizione' => 'Conestat Alfa','id_cas' => 'cf025'],
    //  ['id_principio_attivo' => 'c','descrizione' => 'Ampicillina','id_cas' => ''],
      ['id_principio_attivo' => 'C01AA04','descrizione' => 'Digitossina','id_cas' => 'cf094'],
      ['id_principio_attivo' => 'C01AA05','descrizione' => 'Digossina','id_cas' => 'cf094'],
      ['id_principio_attivo' => 'C01AA08','descrizione' => 'Metildigossina','id_cas' => 'cf094'],
      ['id_principio_attivo' => 'C01BA01','descrizione' => 'Chinidina','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BB02','descrizione' => 'Mexiletina','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BC03','descrizione' => 'Propafenone','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BC04','descrizione' => 'Flecainide','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BD01','descrizione' => 'Amiodarone','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BD04','descrizione' => 'Dofetilide','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BD07','descrizione' => 'Dronedarone','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01BG11','descrizione' => 'Vernakalant','id_cas' => 'cf046'],
      ['id_principio_attivo' => 'C01CA03','descrizione' => 'Norepinefrina','id_cas' => 'cf130'],
      ['id_principio_attivo' => 'C01CA04','descrizione' => 'Dopamina','id_cas' => 'cf130'],
      ['id_principio_attivo' => 'C01DA02','descrizione' => 'Nitroglicerina','id_cas' => 'cf130'],
      ['id_principio_attivo' => 'C01DB01','descrizione' => 'Flosequinan','id_cas' => 'cf130'],
      ['id_principio_attivo' => 'C01EB03','descrizione' => 'Indometacina','id_cas' => 'cf130'],
      ['id_principio_attivo' => 'C01EB15','descrizione' => 'Trimetazidine','id_cas' => 'cf032'],
      ['id_principio_attivo' => 'C01EB16','descrizione' => 'Ibuprofen','id_cas' => 'cf032'],
      ['id_principio_attivo' => 'C01EB17','descrizione' => 'Ivabradine','id_cas' => 'cf032'],
      ['id_principio_attivo' => 'C01EB18','descrizione' => 'Ranolazine','id_cas' => 'cf032'],
      ['id_principio_attivo' => 'C01EB19','descrizione' => 'Icatibant','id_cas' => 'cf032'],
      ['id_principio_attivo' => 'C01EB21','descrizione' => 'Regadenoson','id_cas' => 'cf032'],
      ['id_principio_attivo' => 'C02AC02','descrizione' => 'Guanfacine','id_cas' => 'cf005'],
      ['id_principio_attivo' => 'C02CA04','descrizione' => 'Doxazosin','id_cas' => 'cf006'],
      ['id_principio_attivo' => 'C02DD01','descrizione' => 'Nitroprussiato Di Sodio','id_cas' => 'cf129'],
      ['id_principio_attivo' => 'C02KX01','descrizione' => 'Bosentan','id_cas' => 'cf023'],
      ['id_principio_attivo' => 'C02KX02','descrizione' => 'Ambrisentan','id_cas' => 'cf023'],
      ['id_principio_attivo' => 'C02KX03','descrizione' => 'Sitaxentan','id_cas' => 'cf023'],
      ['id_principio_attivo' => 'C02KX04','descrizione' => 'Macitentan','id_cas' => 'cf023'],
      ['id_principio_attivo' => 'C02KX05','descrizione' => 'Riociguat','id_cas' => 'cf023'],
      ['id_principio_attivo' => 'C03CA01','descrizione' => 'Furosemide','id_cas' => 'cf076'],
      ['id_principio_attivo' => 'C03DA01','descrizione' => 'Spironolattone','id_cas' => 'cf077'],
      ['id_principio_attivo' => 'C03XA01','descrizione' => 'Tolvaptan','id_cas' => 'cf024'],
      ['id_principio_attivo' => 'C04AX21','descrizione' => 'Naftidrofuryl','id_cas' => 'cf139'],
      ['id_principio_attivo' => 'C07AA03','descrizione' => 'Pindololo','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AA05','descrizione' => 'Propranolol','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AA06','descrizione' => 'Timololo','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AA07','descrizione' => 'Sotalolo Cloridrato','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AA12','descrizione' => 'Nadololo','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AB02','descrizione' => 'Metoprololo Tartrato','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AB03','descrizione' => 'Atenololo','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AB04','descrizione' => 'Acebutololo','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AB07','descrizione' => 'Bisoprololo Fumarato','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AB52','descrizione' => 'Metoprolol Combinations','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AG01','descrizione' => 'Labetalolo Cloridrato','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C07AG02','descrizione' => 'Carvedilolo','id_cas' => 'cf085'],
      ['id_principio_attivo' => 'C08CA01','descrizione' => 'Amlodipine','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08CA02','descrizione' => 'Felodipine','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08CA03','descrizione' => 'Isradipina','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08CA04','descrizione' => 'Nicardipine','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08CA05','descrizione' => 'Nifedipine','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08CA08','descrizione' => 'Nitrendipina','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08CA09','descrizione' => 'Lacidipina','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08DA01','descrizione' => 'Verapamil Cloridrato','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08DA02','descrizione' => 'Gallopamil Cloridrato','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C08DB01','descrizione' => 'Diltiazem Cloridrato','id_cas' => 'cf067'],
      ['id_principio_attivo' => 'C09AA01','descrizione' => 'Captopril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA02','descrizione' => 'Enalapril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA03','descrizione' => 'Lisinopril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA04','descrizione' => 'Perindopril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA05','descrizione' => 'Ramipril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA06','descrizione' => 'Quinapril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA07','descrizione' => 'Benazepril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA08','descrizione' => 'Cilazapril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA09','descrizione' => 'Fosinopril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA10','descrizione' => 'Trandolapril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA12','descrizione' => 'Delapril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09AA15','descrizione' => 'Zofenopril','id_cas' => 'cf002'],
      ['id_principio_attivo' => 'C09BA08','descrizione' => 'Cilazapril And Diuretics','id_cas' => 'cf001'],
      ['id_principio_attivo' => 'C09BB03','descrizione' => 'Lisinopril And Amlodipine','id_cas' => 'cf001'],
      ['id_principio_attivo' => 'C09CA01','descrizione' => 'Losartan','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09CA03','descrizione' => 'Valsartan','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09CA04','descrizione' => 'Irbesartan','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09CA06','descrizione' => 'Candesartan','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09CA07','descrizione' => 'Telmisartan','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09CA09','descrizione' => 'Azilsartan Medoxomil','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DA04','descrizione' => 'Irbesartan And Diuretics','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DA06','descrizione' => 'Candesartan And Diuretics','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DA07','descrizione' => 'Telmisartan And Diuretics','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DB01','descrizione' => 'Valsartan And Amlodipine','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DB04','descrizione' => 'Telmisartan And Amlodipine','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DX01','descrizione' => 'Valsartan, Amlodipine And Hydrochlorothiazide','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09DX04','descrizione' => 'Valsartan And Sacubitril','id_cas' => 'cf042'],
      ['id_principio_attivo' => 'C09XA02','descrizione' => 'Aliskiren','id_cas' => 'cf017'],
      ['id_principio_attivo' => 'C09XA52','descrizione' => 'Aliskiren And Hydrochlorothiazide','id_cas' => 'cf017'],
      ['id_principio_attivo' => 'C09XA53','descrizione' => 'Aliskiren And Amlodipine','id_cas' => 'cf017'],
      ['id_principio_attivo' => 'C09XA54','descrizione' => 'Aliskiren, Amlodipine And Hydrochlorothiazide','id_cas' => 'cf017'],
      ['id_principio_attivo' => 'C10AA01','descrizione' => 'Simvastatin','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AA03','descrizione' => 'Pravastatin','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AA04','descrizione' => 'Fluvastatin','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AA05','descrizione' => 'Atorvastatin','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AA06','descrizione' => 'Cerivastatin','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AA07','descrizione' => 'Rosuvastatin','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AB04','descrizione' => 'Gemfibrozil','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AB05','descrizione' => 'Fenofibrate','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AC04','descrizione' => 'Colesevelam','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AD52','descrizione' => 'Nicotinic Acid, Combinations','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AX10','descrizione' => 'Alipogene Tiparvovec','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AX12','descrizione' => 'Lomitapide','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10AX13','descrizione' => 'Other Lipid Modifying Agents','id_cas' => 'cf011'],
      ['id_principio_attivo' => 'C10BA03','descrizione' => 'Pravastatin And Fenofibrate','id_cas' => 'cf010'],
      ['id_principio_attivo' => 'C10BA04','descrizione' => 'Simvastatin And Fenofibrate','id_cas' => 'cf010'],
    //  ['id_principio_attivo' => 'd','descrizione' => 'Aspirina','id_cas' => ''],
      ['id_principio_attivo' => 'D01AC15','descrizione' => 'Fluconazole','id_cas' => 'cf055'],
      ['id_principio_attivo' => 'D02BB02','descrizione' => 'Afamelanotide','id_cas' => 'cf013'],
      ['id_principio_attivo' => 'D03AX06','descrizione' => 'Becaplermin','id_cas' => 'cf069'],
      ['id_principio_attivo' => 'D03BA03','descrizione' => 'Bromelains','id_cas' => 'cf078'],
      ['id_principio_attivo' => 'D05AX52','descrizione' => 'Calcipotriol, Combinations','id_cas' => 'cf064'],
      ['id_principio_attivo' => 'D06AX12','descrizione' => 'Amikacina','id_cas' => 'cf050'],
      ['id_principio_attivo' => 'D06AX13','descrizione' => 'Retapamulin','id_cas' => 'cf050'],
      ['id_principio_attivo' => 'D06BB10','descrizione' => 'Imiquimod','id_cas' => 'cf068'],
      ['id_principio_attivo' => 'D06BX02','descrizione' => 'Ingenol Mebutate','id_cas' => 'cf068'],
      ['id_principio_attivo' => 'D07AA01','descrizione' => 'Metilprednisolone','id_cas' => 'cf072'],
      ['id_principio_attivo' => 'D07AB09','descrizione' => 'Triamcinolone Acetonide','id_cas' => 'cf072'],
      ['id_principio_attivo' => 'D07AC17','descrizione' => 'Fluticasone','id_cas' => 'cf072'],
      ['id_principio_attivo' => 'D10AD04','descrizione' => 'Isotretinoin','id_cas' => 'cf113'],
      ['id_principio_attivo' => 'D11AH01','descrizione' => 'Tacrolimus','id_cas' => 'cf034'],
      ['id_principio_attivo' => 'D11AH02','descrizione' => 'Pimecrolimus','id_cas' => 'cf034'],
      ['id_principio_attivo' => 'D11AX16','descrizione' => 'Eflornithine','id_cas' => 'cf034'],
      ['id_principio_attivo' => 'D11AX21','descrizione' => 'Brimonidine','id_cas' => 'cf034'],
      ['id_principio_attivo' => 'G02CB02','descrizione' => 'Lisuride','id_cas' => 'cf026'],
      ['id_principio_attivo' => 'G02CX01','descrizione' => 'Atosiban','id_cas' => 'cf026'],
      ['id_principio_attivo' => 'G03AA12','descrizione' => 'Drospirenone And Ethinylestradiol','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03AA13','descrizione' => 'Norelgestromin And Ethinylestradiol','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03AA14','descrizione' => 'Nomegestrol And Ethinylestradiol','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03AB05','descrizione' => 'Desogestrel And Estrogen','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03AC08','descrizione' => 'Etonogestrel','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03AD01','descrizione' => 'Levonorgestrel','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03AD02','descrizione' => 'Ulipristal','id_cas' => 'cf070'],
      ['id_principio_attivo' => 'G03BA03','descrizione' => 'Testosterone','id_cas' => 'cf038'],
      ['id_principio_attivo' => 'G03CX','descrizione' => 'Other Estrogens','id_cas' => 'cf080'],
      ['id_principio_attivo' => 'G03DC05','descrizione' => 'Tibolone','id_cas' => 'cf120'],
      ['id_principio_attivo' => 'G03FA01','descrizione' => 'Norethisterone And Estrogen','id_cas' => 'cf121'],
      ['id_principio_attivo' => 'G03GA01','descrizione' => 'Chorionic Gonadotrophin','id_cas' => 'cf095'],
      ['id_principio_attivo' => 'G03GA05','descrizione' => 'Follitropin Alfa','id_cas' => 'cf095'],
      ['id_principio_attivo' => 'G03GA06','descrizione' => 'Follitropin Beta','id_cas' => 'cf095'],
      ['id_principio_attivo' => 'G03GA07','descrizione' => 'Lutropin Alfa','id_cas' => 'cf095'],
      ['id_principio_attivo' => 'G03GA09','descrizione' => 'Corifollitropin Alfa','id_cas' => 'cf095'],
      ['id_principio_attivo' => 'G03HA01','descrizione' => 'Cyproterone','id_cas' => 'cf045'],
      ['id_principio_attivo' => 'G03XB01','descrizione' => 'Mifepristone','id_cas' => 'cf031'],
      ['id_principio_attivo' => 'G03XB02','descrizione' => 'Ulipristal','id_cas' => 'cf031'],
      ['id_principio_attivo' => 'G03XC01','descrizione' => 'Raloxifene','id_cas' => 'cf031'],
      ['id_principio_attivo' => 'G03XC02','descrizione' => 'Bazedoxifene','id_cas' => 'cf031'],
      ['id_principio_attivo' => 'G03XC03','descrizione' => 'Lasofoxifene','id_cas' => 'cf031'],
      ['id_principio_attivo' => 'G03XC05','descrizione' => 'Ospemifene','id_cas' => 'cf031'],
      ['id_principio_attivo' => 'G04BD04','descrizione' => 'Oxybutynin','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BD10','descrizione' => 'Darifenacin','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BD11','descrizione' => 'Fesoterodine','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BD12','descrizione' => 'Mirabegron','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BE03','descrizione' => 'Sildenafil','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BE07','descrizione' => 'Apomorphine','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BE08','descrizione' => 'Tadalafil','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BE09','descrizione' => 'Vardenafil','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04BE10','descrizione' => 'Avanafil','id_cas' => 'cf135'],
      ['id_principio_attivo' => 'G04CA04','descrizione' => 'Silodosin','id_cas' => 'cf093'],
      ['id_principio_attivo' => 'G04CB01','descrizione' => 'Finasteride','id_cas' => 'cf093'],
      ['id_principio_attivo' => 'H01AB01','descrizione' => 'Thyrotropin','id_cas' => 'cf107'],
      ['id_principio_attivo' => 'H01AC01','descrizione' => 'Somatropin','id_cas' => 'cf107'],
      ['id_principio_attivo' => 'H01AC03','descrizione' => 'Mecasermin','id_cas' => 'cf107'],
      ['id_principio_attivo' => 'H01AX01','descrizione' => 'Pegvisomant','id_cas' => 'cf107'],
      ['id_principio_attivo' => 'H01CA03','descrizione' => 'Histrelin','id_cas' => 'cf109'],
      ['id_principio_attivo' => 'H01CB02','descrizione' => 'Octreotide','id_cas' => 'cf109'],
      ['id_principio_attivo' => 'H01CB05','descrizione' => 'Pasireotide','id_cas' => 'cf109'],
      ['id_principio_attivo' => 'H01CC01','descrizione' => 'Ganirelix','id_cas' => 'cf109'],
      ['id_principio_attivo' => 'H02AB02','descrizione' => 'Dexamethasone','id_cas' => 'cf071'],
      ['id_principio_attivo' => 'H02AB06','descrizione' => 'Prednisolone','id_cas' => 'cf071'],
      ['id_principio_attivo' => 'H02AB09','descrizione' => 'Hydrocortisone','id_cas' => 'cf071'],
      ['id_principio_attivo' => 'H02AB10','descrizione' => 'Cortisone','id_cas' => 'cf071'],
      ['id_principio_attivo' => 'H05AA02','descrizione' => 'Teriparatide','id_cas' => 'cf110'],
      ['id_principio_attivo' => 'H05AA03','descrizione' => 'Parathyroid Hormone','id_cas' => 'cf110'],
      ['id_principio_attivo' => 'H05BA01','descrizione' => 'Calcitonin Salmon Synthetic','id_cas' => 'cf008'],
      ['id_principio_attivo' => 'H05BX01','descrizione' => 'Cinacalcet','id_cas' => 'cf008'],
      ['id_principio_attivo' => 'J01AA12','descrizione' => 'Tigecycline','id_cas' => 'cf132'],
      ['id_principio_attivo' => 'J01CA04','descrizione' => 'Amoxicillin','id_cas' => 'cf048'],
      ['id_principio_attivo' => 'J01CE02','descrizione' => 'Fenossimetilpenicillina','id_cas' => 'cf048'],
      ['id_principio_attivo' => 'J01CE08','descrizione' => 'Benzathine Benzylpenicillin','id_cas' => 'cf048'],
      ['id_principio_attivo' => 'J01CR02','descrizione' => 'Amoxicillin And Enzyme Inhibitor','id_cas' => 'cf048'],
      ['id_principio_attivo' => 'J01CR05','descrizione' => 'Piperacillin And Enzyme Inhibitor','id_cas' => 'cf048'],
      ['id_principio_attivo' => 'J01DB01','descrizione' => 'Cefalexina','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DC02','descrizione' => 'Cefuroxime','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DD01','descrizione' => 'Ceftriaxone/Cefotaxime','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DD02','descrizione' => 'Ceftazidime','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DD04','descrizione' => 'Ceftriaxone','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DD13','descrizione' => 'Cefpodoxime','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DE01','descrizione' => 'Cefepima','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DF01','descrizione' => 'Aztreonam','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DH02','descrizione' => 'Meropenem','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DH03','descrizione' => 'Ertapenem','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DH04','descrizione' => 'Doripenem','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DH51','descrizione' => 'Imipenem And Enzyme Inhibitor','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DI01','descrizione' => 'Ceftobiprole Medocaril','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DI02','descrizione' => 'Ceftaroline Fosamil','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01DI54','descrizione' => 'Ceftolozane And Enzyme Inhibitor','id_cas' => 'cf022'],
      ['id_principio_attivo' => 'J01FA09','descrizione' => 'Claritromicina','id_cas' => 'cf103'],
      ['id_principio_attivo' => 'J01FA10','descrizione' => 'Azitromicina','id_cas' => 'cf103'],
      ['id_principio_attivo' => 'J01FA15','descrizione' => 'Telithromycin','id_cas' => 'cf103'],
      ['id_principio_attivo' => 'J01GB01','descrizione' => 'Tobramycin','id_cas' => 'cf047'],
      ['id_principio_attivo' => 'J01MA02','descrizione' => 'Ciprofloxacin','id_cas' => 'cf101'],
      ['id_principio_attivo' => 'J01MA09','descrizione' => 'Sparfloxacin','id_cas' => 'cf101'],
      ['id_principio_attivo' => 'J01MA12','descrizione' => 'Levofloxacin','id_cas' => 'cf101'],
      ['id_principio_attivo' => 'J01MA13','descrizione' => 'Trovafloxacin','id_cas' => 'cf101'],
      ['id_principio_attivo' => 'J01MA14','descrizione' => 'Moxifloxacin','id_cas' => 'cf101'],
      ['id_principio_attivo' => 'J01MA16','descrizione' => 'Gatifloxacin','id_cas' => 'cf101'],
      ['id_principio_attivo' => 'J01XA02','descrizione' => 'Teicoplanin','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XA03','descrizione' => 'Telavancin','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XA04','descrizione' => 'Dalbavancin','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XA05','descrizione' => 'Oritavancin','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XB01','descrizione' => 'Colistin','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XD02','descrizione' => 'Tinidazolo','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XX09','descrizione' => 'Daptomycin','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J01XX11','descrizione' => 'Tedizolid','id_cas' => 'cf021'],
      ['id_principio_attivo' => 'J02AB02','descrizione' => 'Ketoconazole','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AC01','descrizione' => 'Fluconazole','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AC03','descrizione' => 'Voriconazole','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AC04','descrizione' => 'Posaconazole','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AC05','descrizione' => 'Isavuconazole','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AX04','descrizione' => 'Caspofungin','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AX05','descrizione' => 'Micafungin','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J02AX06','descrizione' => 'Anidulafungin','id_cas' => 'cf061'],
      ['id_principio_attivo' => 'J04AA01','descrizione' => '4-Aminosalicylic Acid','id_cas' => 'cf090'],
      ['id_principio_attivo' => 'J04AK05','descrizione' => 'Bedaquiline','id_cas' => 'cf090'],
      ['id_principio_attivo' => 'J04AK06','descrizione' => 'Delamanid','id_cas' => 'cf090'],
      ['id_principio_attivo' => 'J05AB04','descrizione' => 'Ribavirin','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AB06','descrizione' => 'Ganciclovir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AB09','descrizione' => 'Famciclovir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AB11','descrizione' => 'Valaciclovir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AB12','descrizione' => 'Cidofovir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE01','descrizione' => 'Saquinavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE02','descrizione' => 'Indinavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE03','descrizione' => 'Ritonavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE04','descrizione' => 'Nelfinavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE05','descrizione' => 'Amprenavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE07','descrizione' => 'Fosamprenavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE08','descrizione' => 'Atazanavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE09','descrizione' => 'Tipranavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE10','descrizione' => 'Darunavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE11','descrizione' => 'Telaprevir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE12','descrizione' => 'Boceprevir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AE14','descrizione' => 'Simeprevir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF04','descrizione' => 'Stavudine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF05','descrizione' => 'Lamivudine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF06','descrizione' => 'Abacavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF07','descrizione' => 'Tenofovir Disoproxil','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF08','descrizione' => 'Adefovir Dipivoxil','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF09','descrizione' => 'Emtricitabine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF10','descrizione' => 'Entecavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AF11','descrizione' => 'Telbivudine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AG01','descrizione' => 'Nevirapine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AG03','descrizione' => 'Efavirenz','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AG04','descrizione' => 'Etravirine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AG05','descrizione' => 'Rilpivirine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AH02','descrizione' => 'Oseltamivir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR01','descrizione' => 'Zidovudine And Lamivudine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR02','descrizione' => 'Lamivudine And Abacavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR03','descrizione' => 'Tenofovir Disoproxil And Emtricitabine','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR06','descrizione' => 'Emtricitabine, Tenofovir Disoproxil And Efavirenz','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR08','descrizione' => 'Emtricitabine, Rilpivirine And Tenofovir Disoproxil','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR09','descrizione' => 'Emtricitabine, Tenofovir Disoproxil, Elvitegravir And Cobicistat','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR10','descrizione' => 'Lopinavir And Ritonavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR13','descrizione' => 'Lamivudine, Abacavir And Dolutegravir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR14','descrizione' => 'Darunavir And Cobicistat','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR15','descrizione' => 'Atazanavir And Cobicistat','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR16','descrizione' => 'Lamivudine And Raltegravir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR17','descrizione' => 'Emtricitabine And Tenofovir Alafenamide','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AR18','descrizione' => 'Emtricitabine, Tenofovir Alafenamide, Elvitegravir And Cobicistat','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX07','descrizione' => 'Enfuvirtide','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX08','descrizione' => 'Raltegravir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX09','descrizione' => 'Maraviroc','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX11','descrizione' => 'Elvitegravir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX12','descrizione' => 'Dolutegravir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX14','descrizione' => 'Daclatasvir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX15','descrizione' => 'Sofosbuvir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX16','descrizione' => 'Dasabuvir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX65','descrizione' => 'Sofosbuvir And Ledipasvir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J05AX67','descrizione' => 'Ombitasvir, Paritaprevir And Ritonavir','id_cas' => 'cf084'],
      ['id_principio_attivo' => 'J06BA01','descrizione' => 'Immunoglobulins, Normal Human, For Extravascular Administration','id_cas' => 'cf096'],
      ['id_principio_attivo' => 'J06BA02','descrizione' => 'Immunoglobulins, Normal Human, For Intravascular Administration','id_cas' => 'cf096'],
      ['id_principio_attivo' => 'J06BB04','descrizione' => 'Hepatitis B Immunoglobulin','id_cas' => 'cf096'],
      ['id_principio_attivo' => 'J06BB16','descrizione' => 'Palivizumab','id_cas' => 'cf096'],
      ['id_principio_attivo' => 'J07AE01','descrizione' => 'Cholera, Inactivated, Whole Cell','id_cas' => 'cf136'],
      ['id_principio_attivo' => 'J07AG01','descrizione' => 'Hemophilus Influenzae B, Purified Antigen Conjugated','id_cas' => 'cf136'],
      ['id_principio_attivo' => 'J07AH08','descrizione' => 'Meningococcus, Tetravalent Purified Polysaccharides Antigen Conjugated','id_cas' => 'cf136'],
      ['id_principio_attivo' => 'J07AH09','descrizione' => 'Meningococcus B, Multicomponent Vaccine','id_cas' => 'cf136'],
      ['id_principio_attivo' => 'J07AL02','descrizione' => 'Pneumococcus, Purified Polysaccharides Antigen Conjugated','id_cas' => 'cf136'],
      ['id_principio_attivo' => 'J07AL52','descrizione' => 'Pneumococcus Purified Polysaccharides Antigen And Haemophilus Influenzae, Conjugated','id_cas' => 'cf136'],
      ['id_principio_attivo' => 'J07BA02','descrizione' => 'Encephalitis, Japanese, Inactivated, Whole Virus','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BB01','descrizione' => 'Influenza, Inactivated, Whole Virus','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BB02','descrizione' => 'Influenza, Purified Antigen','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BB03','descrizione' => 'Influenza, Live Attenuated','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BC01','descrizione' => 'Hepatitis B, Purified Antigen','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BC20','descrizione' => 'Combinations','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BD52','descrizione' => 'Measles, Combinations With Mumps And Rubella, Live Attenuated','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BD54','descrizione' => 'Measles, Combinations With Mumps, Rubella And Varicella, Live Attenuated','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BH01','descrizione' => 'Rota Virus, Live Attenuated','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BH02','descrizione' => 'Rota Virus, Pentavalent, Live, Reassorted','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BK02','descrizione' => 'Zoster, Live Attenuated','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BL01','descrizione' => 'Yellow Fever, Live Attenuated','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BM01','descrizione' => 'Papillomavirus (Human Types 6, 11, 16, 18) Papillomavirus (Human Types 16, 18)','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BM02','descrizione' => 'Papillomavirus (Human Types 16, 18)','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07BM03','descrizione' => 'Papillomavirus (Human Types 6, 11, 16, 18, 31, 33, 45, 52, 58)','id_cas' => 'cf137'],
      ['id_principio_attivo' => 'J07CA01','descrizione' => 'Diphtheria-Poliomyelitis-Tetanus','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'J07CA05','descrizione' => 'Diphtheria-Hepatitis B-Pertussis-Tetanus','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'J07CA07','descrizione' => 'Diphtheria-Hepatitis B-Tetanus','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'J07CA08','descrizione' => 'Hemophilus Influenzae B And Hepatitis B','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'J07CA09','descrizione' => 'Diphtheria-Hemophilus Influenzae B-Pertussis-Poliomyelitis-Tetanus-Hepatitis B','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'J07CA10','descrizione' => 'Typhoid-Hepatitis A','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'J07CA12','descrizione' => 'Diphtheria-Pertussis-Poliomyelitis-Tetanus-Hepatitis B','id_cas' => 'cf138'],
      ['id_principio_attivo' => 'L01AB01','descrizione' => 'Busulfan','id_cas' => 'cf081'],
      ['id_principio_attivo' => 'L01AC01','descrizione' => 'Thiotepa','id_cas' => 'cf081'],
      ['id_principio_attivo' => 'L01AX03','descrizione' => 'Temozolomide','id_cas' => 'cf081'],
      ['id_principio_attivo' => 'L01AX04','descrizione' => 'Dacarbazine','id_cas' => 'cf081'],
      ['id_principio_attivo' => 'L01BA04','descrizione' => 'Pemetrexed','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BA05','descrizione' => 'Pralatrexate','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BB02','descrizione' => 'Mercaptopurine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BB04','descrizione' => 'Cladribine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BB06','descrizione' => 'Clofarabine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BB07','descrizione' => 'Nelarabine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BC01','descrizione' => 'Cytarabine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BC05','descrizione' => 'Gemcitabine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BC06','descrizione' => 'Capecitabine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BC07','descrizione' => 'Azacitidine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BC08','descrizione' => 'Decitabine','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01BC53','descrizione' => 'Tegafur, Combinations','id_cas' => 'cf060'],
      ['id_principio_attivo' => 'L01CA05','descrizione' => 'Vinflunine','id_cas' => 'cf014'],
      ['id_principio_attivo' => 'L01CA06','descrizione' => 'Vintafolide','id_cas' => 'cf014'],
      ['id_principio_attivo' => 'L01CD01','descrizione' => 'Paclitaxel','id_cas' => 'cf014'],
      ['id_principio_attivo' => 'L01CD02','descrizione' => 'Docetaxel','id_cas' => 'cf014'],
      ['id_principio_attivo' => 'L01CD04','descrizione' => 'Cabazitaxel','id_cas' => 'cf014'],
      ['id_principio_attivo' => 'L01CX01','descrizione' => 'Trabectedin','id_cas' => 'cf014'],
      ['id_principio_attivo' => 'L01DB01','descrizione' => 'Doxorubicin','id_cas' => 'cf049'],
      ['id_principio_attivo' => 'L01DB11','descrizione' => 'Pixantrone','id_cas' => 'cf049'],
      ['id_principio_attivo' => 'L01XC02','descrizione' => 'Rituximab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC03','descrizione' => 'Trastuzumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC04','descrizione' => 'Alemtuzumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC06','descrizione' => 'Cetuximab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC07','descrizione' => 'Bevacizumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC08','descrizione' => 'Panitumumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC09','descrizione' => 'Catumaxomab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC10','descrizione' => 'Ofatumumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC11','descrizione' => 'Ipilimumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC12','descrizione' => 'Brentuximab Vedotin','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC13','descrizione' => 'Pertuzumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC14','descrizione' => 'Trastuzumab Emtansine','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC15','descrizione' => 'Obinutuzumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC16','descrizione' => 'Dinutuximab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC17','descrizione' => 'Nivolumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC18','descrizione' => 'Pembrolizumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC19','descrizione' => 'Blinatumomab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC21','descrizione' => 'Ramucirumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC22','descrizione' => 'Necitumumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XC24','descrizione' => 'Daratumumab','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XD01','descrizione' => 'Porfimer Sodium','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XD04','descrizione' => 'Aminolevulinic Acid','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XD05','descrizione' => 'Temoporfin','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE01','descrizione' => 'Imatinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE02','descrizione' => 'Gefitinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE03','descrizione' => 'Erlotinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE04','descrizione' => 'Sunitinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE05','descrizione' => 'Sorafenib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE06','descrizione' => 'Dasatinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE07','descrizione' => 'Lapatinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE08','descrizione' => 'Nilotinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE09','descrizione' => 'Temsirolimus','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE10','descrizione' => 'Everolimus','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE11','descrizione' => 'Pazopanib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE12','descrizione' => 'Vandetanib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE13','descrizione' => 'Afatinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE14','descrizione' => 'Bosutinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE15','descrizione' => 'Vemurafenib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE16','descrizione' => 'Crizotinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE17','descrizione' => 'Axitinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE18','descrizione' => 'Ruxolitinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE21','descrizione' => 'Regorafenib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE22','descrizione' => 'Masitinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE23','descrizione' => 'Dabrafenib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE24','descrizione' => 'Ponatinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE25','descrizione' => 'Trametinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE26','descrizione' => 'Cabozantinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE27','descrizione' => 'Ibrutinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE29','descrizione' => 'Lenvatinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE31','descrizione' => 'Nintedanib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE35','descrizione' => 'Osimertinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XE38','descrizione' => 'Cobimetinib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX02','descrizione' => 'Asparaginase','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX05','descrizione' => 'Hydroxycarbamide','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX17','descrizione' => 'Topotecan','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX22','descrizione' => 'Alitretinoin','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX23','descrizione' => 'Mitotane','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX24','descrizione' => 'Pegaspargase','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX25','descrizione' => 'Bexarotene','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX27','descrizione' => 'Arsenic Trioxide','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX32','descrizione' => 'Bortezomib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX33','descrizione' => 'Celecoxib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX35','descrizione' => 'Anagrelide','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX39','descrizione' => 'Romidepsin','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX41','descrizione' => 'Eribulin','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX42','descrizione' => 'Panobinostat','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX43','descrizione' => 'Vismodegib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX44','descrizione' => 'Aflibercept','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX45','descrizione' => 'Carfilzomib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX47','descrizione' => 'Idelalisib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L01XX48','descrizione' => 'Sonidegib','id_cas' => 'cf018'],
      ['id_principio_attivo' => 'L02AE03','descrizione' => 'Goserelin','id_cas' => 'cf108'],
      ['id_principio_attivo' => 'L02BA02','descrizione' => 'Toremifene','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BA03','descrizione' => 'Fulvestrant','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BB03','descrizione' => 'Bicalutamide','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BB04','descrizione' => 'Enzalutamide','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BG03','descrizione' => 'Anastrozole','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BG04','descrizione' => 'Letrozole','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BX02','descrizione' => 'Degarelix','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L02BX03','descrizione' => 'Abiraterone','id_cas' => 'cf043'],
      ['id_principio_attivo' => 'L03AA02','descrizione' => 'Filgrastim','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AA03','descrizione' => 'Molgramostim','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AA13','descrizione' => 'Pegfilgrastim','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AA14','descrizione' => 'Lipegfilgrastim','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AA15','descrizione' => 'Balugrastim','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB01','descrizione' => 'Interferon Alfa Natural','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB05','descrizione' => 'Interferon Alfa-2B','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB07','descrizione' => 'Interferon Beta-1A','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB08','descrizione' => 'Interferon Beta-1B','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB09','descrizione' => 'Interferon Alfacon-1','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB10','descrizione' => 'Peginterferon Alfa-2B','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB11','descrizione' => 'Peginterferon Alfa-2A','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AB13','descrizione' => 'Peginterferon Beta-1A','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AX11','descrizione' => 'Tasonermin','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AX14','descrizione' => 'Histamine Dihydrochloride','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AX15','descrizione' => 'Mifamurtide','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AX16','descrizione' => 'Plerixafor','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AX17','descrizione' => 'Sipuleucel-T','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L03AX19','descrizione' => 'Dasiprotimut-T','id_cas' => 'cf098'],
      ['id_principio_attivo' => 'L04AA02','descrizione' => 'Muromonab-Cd3','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA06','descrizione' => 'Mycophenolic Acid','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA10','descrizione' => 'Sirolimus','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA13','descrizione' => 'Leflunomide','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA21','descrizione' => 'Efalizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA23','descrizione' => 'Natalizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA24','descrizione' => 'Abatacept','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA25','descrizione' => 'Eculizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA26','descrizione' => 'Belimumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA27','descrizione' => 'Fingolimod','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA28','descrizione' => 'Belatacept','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA29','descrizione' => 'Tofacitinib','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA31','descrizione' => 'Teriflunomide','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA32','descrizione' => 'Apremilast','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA33','descrizione' => 'Vedolizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AA34','descrizione' => 'Alemtuzumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AB01','descrizione' => 'Etanercept','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AB02','descrizione' => 'Infliximab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AB04','descrizione' => 'Adalimumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AB05','descrizione' => 'Certolizumab Pegol','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AB06','descrizione' => 'Golimumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC01','descrizione' => 'Daclizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC03','descrizione' => 'Anakinra','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC04','descrizione' => 'Rilonacept','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC05','descrizione' => 'Ustekinumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC07','descrizione' => 'Tocilizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC08','descrizione' => 'Canakinumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC10','descrizione' => 'Secukinumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC11','descrizione' => 'Siltuximab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AC13','descrizione' => 'Ixekizumab','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AD02','descrizione' => 'Tacrolimus','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AD03','descrizione' => 'Voclosporin','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AX02','descrizione' => 'Thalidomide','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AX04','descrizione' => 'Lenalidomide','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AX05','descrizione' => 'Pirfenidone','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'L04AX06','descrizione' => 'Pomalidomide','id_cas' => 'cf097'],
      ['id_principio_attivo' => 'M01AA01','descrizione' => 'Fenilbutazone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AA02','descrizione' => 'Mofebutazone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AA03','descrizione' => 'Oxifenbutazone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AA05','descrizione' => 'Clofezone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AA06','descrizione' => 'Kebuzone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AA90','descrizione' => 'Suxibuzone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AA99','descrizione' => 'Combinazione','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB01','descrizione' => 'Indometacina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB02','descrizione' => 'Sulindac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB03','descrizione' => 'Tolmetina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB04','descrizione' => 'Zomepirac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB05','descrizione' => 'Diclofenac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB06','descrizione' => 'Alclofenac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB07','descrizione' => 'Bumadizone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB08','descrizione' => 'Etodolac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB09','descrizione' => 'Lonazolac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB10','descrizione' => 'Fentiazac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB11','descrizione' => 'Acemetacina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB12','descrizione' => 'Difenpiramide','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB13','descrizione' => 'Oxametacina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB14','descrizione' => 'Proglumetacina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB15','descrizione' => 'Ketorolac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB16','descrizione' => 'Aceclofenac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB17','descrizione' => 'Bufexamac','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB51','descrizione' => 'Indometacina, Combinazioni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AB55','descrizione' => 'Diclofenac, Combinazioni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AC01','descrizione' => 'Piroxicam','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AC02','descrizione' => 'Tenoxicam','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AC04','descrizione' => 'Droxicam','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AC05','descrizione' => 'Lornoxicam','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AC06','descrizione' => 'Meloxicam','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AC56','descrizione' => 'Meloxicam, Combinazioni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE01','descrizione' => 'Ibuprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE02','descrizione' => 'Naproxene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE03','descrizione' => 'Ketoprofen','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE04','descrizione' => 'Fenoprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE05','descrizione' => 'Fenbufene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE06','descrizione' => 'Benoxaprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE07','descrizione' => 'Suprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE08','descrizione' => 'Pirprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE09','descrizione' => 'Flurbiprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE10','descrizione' => 'Indoprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE11','descrizione' => 'Acido Tiaprofenico','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE12','descrizione' => 'Oxaprozina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE13','descrizione' => 'Ibuproxam','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE14','descrizione' => 'Dexibuprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE15','descrizione' => 'Flunoxaprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE16','descrizione' => 'Alminoprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE17','descrizione' => 'Dexketoprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE18','descrizione' => 'Naproxcinod','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE51','descrizione' => 'Ibuprofene, Combinazioni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE52','descrizione' => 'Naproxen E Esomeprazolo','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE53','descrizione' => 'Ketoprofene, Combinazioni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE56','descrizione' => 'Naproxen E Misoprostol','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE90','descrizione' => 'Vedaprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE91','descrizione' => 'Carprofene','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AE92','descrizione' => 'Tepoxalin','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AG01','descrizione' => 'Acido Mefenamico','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AG02','descrizione' => 'Acido Tolfenamico','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AG03','descrizione' => 'Acido Flufenamico','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AG04','descrizione' => 'Acido Meclofenamico','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AG90','descrizione' => 'Funixina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH01','descrizione' => 'Celecoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH02','descrizione' => 'Rofecoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH03','descrizione' => 'Valdecoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH04','descrizione' => 'Parecoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH05','descrizione' => 'Etoricoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH06','descrizione' => 'Lumiracoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH90','descrizione' => 'Firocoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH91','descrizione' => 'Robenacoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH92','descrizione' => 'Mavacoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH93','descrizione' => 'Cimicoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AH94','descrizione' => 'Deracoxib','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX01','descrizione' => 'Nabumetone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX02','descrizione' => 'Acido Niflumico','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX04','descrizione' => 'Azapropazone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX05','descrizione' => 'Glucosamine','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX07','descrizione' => 'Benzidamina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX12','descrizione' => 'Glicosaminoglicano Polisolfato','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX13','descrizione' => 'Proquazone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX14','descrizione' => 'Orgoteina','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX17','descrizione' => 'Nimesulide','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX18','descrizione' => 'Feprazone','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX21','descrizione' => 'Diacerein','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX22','descrizione' => 'Morniflumato','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX23','descrizione' => 'Tenidap','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX24','descrizione' => 'Oxaceprolo','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX25','descrizione' => 'Condroitina Solfato','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX26','descrizione' => 'Olio Di Avocado E Olio Di Soia, Insaponificabili','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX52','descrizione' => 'Acido Niflumico, Combinaizoni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX68','descrizione' => 'Feprazone, Combinaizoni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX90','descrizione' => 'Pentosan Polisolfato','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX91','descrizione' => 'Aminopropionitrile','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M01AX99','descrizione' => 'Combinaizoni','id_cas' => 'cf119'],
      ['id_principio_attivo' => 'M03AX01','descrizione' => 'Botulinum Toxin','id_cas' => 'cf124'],
      ['id_principio_attivo' => 'M03BA02','descrizione' => 'Carisoprodol','id_cas' => 'cf123'],
      ['id_principio_attivo' => 'M03BB02','descrizione' => 'Chlormezanone','id_cas' => 'cf123'],
      ['id_principio_attivo' => 'M03BX04','descrizione' => 'Tolperisone','id_cas' => 'cf123'],
      ['id_principio_attivo' => 'M03BX05','descrizione' => 'Thiocolchicoside','id_cas' => 'cf123'],
      ['id_principio_attivo' => 'M03BX07','descrizione' => 'Tetrazepam','id_cas' => 'cf123'],
      ['id_principio_attivo' => 'M04AA03','descrizione' => 'Febuxostat','id_cas' => 'cf115'],
      ['id_principio_attivo' => 'M04AB05','descrizione' => 'Lesinurad','id_cas' => 'cf115'],
      ['id_principio_attivo' => 'M04AX02','descrizione' => 'Pegloticase','id_cas' => 'cf115'],
      ['id_principio_attivo' => 'M05BA04','descrizione' => 'Alendronic Acid','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BA06','descrizione' => 'Ibandronic Acid','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BA08','descrizione' => 'Zoledronic Acid','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BB03','descrizione' => 'Alendronic Acid And Colecalciferol','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BB04','descrizione' => 'Risedronic Acid, Calcium And Colecalciferol, Sequential','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BC01','descrizione' => 'Dibotermin Alfa','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BC02','descrizione' => 'Eptotermin Alfa','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BX03','descrizione' => 'Strontium Ranelate','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M05BX04','descrizione' => 'Denosumab','id_cas' => 'cf086'],
      ['id_principio_attivo' => 'M09AB02','descrizione' => 'Collagenase Clostridium Histolyticum','id_cas' => 'cf027'],
      ['id_principio_attivo' => 'M09AX02','descrizione' => 'Chondrocytes, Autologous','id_cas' => 'cf027'],
      ['id_principio_attivo' => 'M09AX03','descrizione' => 'Ataluren','id_cas' => 'cf027'],
      ['id_principio_attivo' => 'N01AH01','descrizione' => 'Fentanyl','id_cas' => 'cf039'],
      ['id_principio_attivo' => 'N01AH03','descrizione' => 'Sufentanil','id_cas' => 'cf039'],
      ['id_principio_attivo' => 'N01BB02','descrizione' => 'Lidocaina','id_cas' => 'cf040'],
      ['id_principio_attivo' => 'N01BB20','descrizione' => 'Amides, Combinations','id_cas' => 'cf040'],
      ['id_principio_attivo' => 'N01BB52','descrizione' => 'Lidocaine, Combinations','id_cas' => 'cf040'],
      ['id_principio_attivo' => 'N01BX04','descrizione' => 'Capsaicin','id_cas' => 'cf040'],
      ['id_principio_attivo' => 'N02AA01','descrizione' => 'Morfina','id_cas' => 'cf106'],
      ['id_principio_attivo' => 'N02AB03','descrizione' => 'Fentanyl','id_cas' => 'cf106'],
      ['id_principio_attivo' => 'N02AC54','descrizione' => 'Dextropropoxyphene, Combinations Excluding Psycholept','id_cas' => 'cf106'],
      ['id_principio_attivo' => 'N02AX02','descrizione' => 'Tramadol','id_cas' => 'cf106'],
      ['id_principio_attivo' => 'N02BE01','descrizione' => 'Paracetamolo/Tachipirina','id_cas' => 'cf020'],
      ['id_principio_attivo' => 'N02BG07','descrizione' => 'Flupirtine','id_cas' => 'cf020'],
      ['id_principio_attivo' => 'N02BG08','descrizione' => 'Ziconotide','id_cas' => 'cf020'],
      ['id_principio_attivo' => 'N02CA02','descrizione' => 'Ergotamina','id_cas' => 'cf114'],
      ['id_principio_attivo' => 'N02CC01','descrizione' => 'Sumatriptan','id_cas' => 'cf114'],
      ['id_principio_attivo' => 'N02CC03','descrizione' => 'Zolmitriptan','id_cas' => 'cf114'],
      ['id_principio_attivo' => 'N02CX04','descrizione' => 'Sumatriptan','id_cas' => 'cf114'],
      ['id_principio_attivo' => 'N03AF01','descrizione' => 'Carbamazepina','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AF03','descrizione' => 'Rufinamide','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AF04','descrizione' => 'Eslicarbazepine','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AG01','descrizione' => 'Valproic Acid','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AG04','descrizione' => 'Vigabatrin','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX09','descrizione' => 'Lamotrigine','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX11','descrizione' => 'Topiramate','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX12','descrizione' => 'Gabapentin','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX14','descrizione' => 'Levetiracetam','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX15','descrizione' => 'Zonisamide','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX16','descrizione' => 'Pregabalin','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX17','descrizione' => 'Stiripentol','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX18','descrizione' => 'Lacosamide','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX21','descrizione' => 'Retigabine','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX22','descrizione' => 'Perampanel','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N03AX23','descrizione' => 'Brivaracetam','id_cas' => 'cf053'],
      ['id_principio_attivo' => 'N04BA02','descrizione' => 'Levodopa And Decarboxylase Inhibitor','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BA03','descrizione' => 'Levodopa, Decarboxylase Inhibitor And Comt Inhibitor','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BC04','descrizione' => 'Ropinirole','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BC05','descrizione' => 'Pramipexole','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BC09','descrizione' => 'Rotigotine','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BD02','descrizione' => 'Rasagiline','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BX01','descrizione' => 'Tolcapone','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N04BX02','descrizione' => 'Entacapone','id_cas' => 'cf009'],
      ['id_principio_attivo' => 'N05AB04','descrizione' => 'Proclorperazina','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AE03','descrizione' => 'Sertindole','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AE05','descrizione' => 'Lurasidone','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AH01','descrizione' => 'Loxapine','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AH02','descrizione' => 'Clozapine','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AH03','descrizione' => 'Olanzapine','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AH04','descrizione' => 'Quetiapine','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AH05','descrizione' => 'Asenapine','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AL06','descrizione' => 'Veralipride','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AL07','descrizione' => 'Levosulpiride','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AX08','descrizione' => 'Risperidone','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AX12','descrizione' => 'Aripiprazole','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AX13','descrizione' => 'Paliperidone','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05AX14','descrizione' => 'Iloperidone','id_cas' => 'cf063'],
      ['id_principio_attivo' => 'N05BA12','descrizione' => 'Alprazolam','id_cas' => 'cf041'],
      ['id_principio_attivo' => 'N05CD08','descrizione' => 'Midazolam','id_cas' => 'cf100'],
      ['id_principio_attivo' => 'N05CF03','descrizione' => 'Zaleplon','id_cas' => 'cf100'],
      ['id_principio_attivo' => 'N05CF04','descrizione' => 'Eszopiclone','id_cas' => 'cf100'],
      ['id_principio_attivo' => 'N05CH01','descrizione' => 'Melatonin','id_cas' => 'cf100'],
      ['id_principio_attivo' => 'N05CH03','descrizione' => 'Tasimelteon','id_cas' => 'cf100'],
      ['id_principio_attivo' => 'N05CM18','descrizione' => 'Dexmedetomidine','id_cas' => 'cf100'],
      ['id_principio_attivo' => 'N06AA01','descrizione' => 'Desipramina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA02','descrizione' => 'Imipramina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA03','descrizione' => 'Imipramina Ossido','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA04','descrizione' => 'Clomipramina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA05','descrizione' => 'Opipramol','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA06','descrizione' => 'Trimipramina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA07','descrizione' => 'Lofepramina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA08','descrizione' => 'Dibenzepin','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA09','descrizione' => 'Amitriptilina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA10','descrizione' => 'Nortriptilina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA11','descrizione' => 'Protriptilina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA12','descrizione' => 'Doxepina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA13','descrizione' => 'Iprindolo','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA14','descrizione' => 'Melitracene','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA15','descrizione' => 'Butriptilina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA16','descrizione' => 'Dosulepina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA17','descrizione' => 'Amoxapina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA18','descrizione' => 'Dimetacrina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA19','descrizione' => 'Amineptina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA21','descrizione' => 'Maprotilina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AA23','descrizione' => 'Quinupramina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB02','descrizione' => 'Zimelidina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB03','descrizione' => 'Fluoxetine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB04','descrizione' => 'Citalopram','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB05','descrizione' => 'Paroxetine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB06','descrizione' => 'Sertraline','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB07','descrizione' => 'Alaproclato','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB08','descrizione' => 'Fluvoxamine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB09','descrizione' => 'Etoperidone','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AB10','descrizione' => 'Escitalopram','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AF01','descrizione' => 'Isocarboxazide','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AF02','descrizione' => 'Nialamide','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AF03','descrizione' => 'Fenelzina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AF04','descrizione' => 'Tranilcipromina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AF05','descrizione' => 'Iproniazide','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AF06','descrizione' => 'Iproclozide','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AG02','descrizione' => 'Moclobemide','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AG03','descrizione' => 'Toloxatone','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX01','descrizione' => 'Oxitriptan','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX02','descrizione' => 'Triptofano','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX03','descrizione' => 'Mianserina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX04','descrizione' => 'Nomifensina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX05','descrizione' => 'Trazodone','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX06','descrizione' => 'Nefazodone','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX07','descrizione' => 'Minaprina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX08','descrizione' => 'Bifemelano','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX09','descrizione' => 'Viloxazina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX10','descrizione' => 'Oxaflozan','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX11','descrizione' => 'Mirtazapine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX12','descrizione' => 'Bupropion','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX13','descrizione' => 'Medifoxamina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX14','descrizione' => 'Tianeptina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX15','descrizione' => 'Pivagabina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX16','descrizione' => 'Venlafaxine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX17','descrizione' => 'Milnacipran','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX18','descrizione' => 'Reboxetine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX19','descrizione' => 'Gepirone','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX21','descrizione' => 'Duloxetine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX22','descrizione' => 'Agomelatine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX23','descrizione' => 'Desvenlafaxina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX24','descrizione' => 'Vilazodone','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX25','descrizione' => 'Hypericum','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX26','descrizione' => 'Vortioxetine','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06AX90','descrizione' => 'Selegilina','id_cas' => 'cf051'],
      ['id_principio_attivo' => 'N06BA04','descrizione' => 'Methylphenidate','id_cas' => 'cf122'],
      ['id_principio_attivo' => 'N06BA07','descrizione' => 'Modafinil','id_cas' => 'cf122'],
      ['id_principio_attivo' => 'N06BA09','descrizione' => 'Atomoxetine','id_cas' => 'cf122'],
      ['id_principio_attivo' => 'N06BC01','descrizione' => 'Caffeine','id_cas' => 'cf122'],
      ['id_principio_attivo' => 'N06BC02','descrizione' => 'Propentofylline','id_cas' => 'cf122'],
      ['id_principio_attivo' => 'N06DA03','descrizione' => 'Rivastigmine','id_cas' => 'cf082'],
      ['id_principio_attivo' => 'N06DA04','descrizione' => 'Galantamine','id_cas' => 'cf082'],
      ['id_principio_attivo' => 'N06DA52','descrizione' => 'Donepezil And Memantine','id_cas' => 'cf082'],
      ['id_principio_attivo' => 'N06DX01','descrizione' => 'Memantine','id_cas' => 'cf082'],
      ['id_principio_attivo' => 'N07BA03','descrizione' => 'Varenicline','id_cas' => 'cf092'],
      ['id_principio_attivo' => 'N07BB05','descrizione' => 'Nalmefene','id_cas' => 'cf092'],
      ['id_principio_attivo' => 'N07BC03','descrizione' => 'Levacetylmethadol','id_cas' => 'cf092'],
      ['id_principio_attivo' => 'N07BC51','descrizione' => 'Buprenorphine, Combinations','id_cas' => 'cf092'],
      ['id_principio_attivo' => 'N07CA01','descrizione' => 'Betahistine','id_cas' => 'cf116'],
      ['id_principio_attivo' => 'N07XX02','descrizione' => 'Riluzole','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX04','descrizione' => 'Hydroxybutyric Acid','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX05','descrizione' => 'Amifampridine','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX07','descrizione' => 'Fampridine','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX08','descrizione' => 'Tafamidis','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX09','descrizione' => 'Dimethyl Fumarate','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX11','descrizione' => 'Pitolisant','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'N07XX59','descrizione' => 'Dextromethorphan, Combinations','id_cas' => 'cf015'],
      ['id_principio_attivo' => 'P01BF05','descrizione' => 'Artenimol And Piperaquine','id_cas' => 'cf059'],
      ['id_principio_attivo' => 'R01AD04','descrizione' => 'Flunisolide','id_cas' => 'cf074'],
      ['id_principio_attivo' => 'R01AD09','descrizione' => 'Mometasone','id_cas' => 'cf074'],
      ['id_principio_attivo' => 'R01AD12','descrizione' => 'Flucticasone Furoate','id_cas' => 'cf074'],
      ['id_principio_attivo' => 'R01AD13','descrizione' => 'Ciclesonide','id_cas' => 'cf074'],
      ['id_principio_attivo' => 'R01AX03','descrizione' => 'Ipratropio','id_cas' => 'cf074'],
      ['id_principio_attivo' => 'R03AC02','descrizione' => 'Salbutamol','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AC07','descrizione' => 'Isoetarine','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AC12','descrizione' => 'Salmeterolo','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AC13','descrizione' => 'Formoterol','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AC18','descrizione' => 'Indacaterol','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AK06','descrizione' => 'Salmeterol And Other Drugs For Obstructive Airway Diseases','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AK07','descrizione' => 'Formoterol And Budesonide','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AK10','descrizione' => 'Vilanterol And Fluticasone Furoate','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AL02','descrizione' => 'Salbutamolo Solfato+Ipratropio Bromuro','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AL03','descrizione' => 'Vilanterol And Umeclidinium Bromide','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AL04','descrizione' => 'Indacaterol And Glycopyrronium Bromide','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03AL05','descrizione' => 'Formoterol And Aclidinium Bromide','id_cas' => 'cf004'],
      ['id_principio_attivo' => 'R03BA02','descrizione' => 'Budesonide','id_cas' => 'cf028'],
      ['id_principio_attivo' => 'R03BA08','descrizione' => 'Ciclesonide','id_cas' => 'cf028'],
      ['id_principio_attivo' => 'R03BB05','descrizione' => 'Aclidinium Bromide','id_cas' => 'cf028'],
      ['id_principio_attivo' => 'R03BB06','descrizione' => 'Glycopyrronium Bromide','id_cas' => 'cf028'],
      ['id_principio_attivo' => 'R03BB07','descrizione' => 'Umeclidinium Bromide','id_cas' => 'cf028'],
      ['id_principio_attivo' => 'R03CA','descrizione' => 'Alpha- And Beta-Adrenoceptor Agonists','id_cas' => 'cf003'],
      ['id_principio_attivo' => 'R03DA04','descrizione' => 'Teofillina','id_cas' => 'cf029'],
      ['id_principio_attivo' => 'R03DC01','descrizione' => 'Zafirlukast','id_cas' => 'cf029'],
      ['id_principio_attivo' => 'R03DC03','descrizione' => 'Montelukast','id_cas' => 'cf029'],
      ['id_principio_attivo' => 'R03DX05','descrizione' => 'Omalizumab','id_cas' => 'cf029'],
      ['id_principio_attivo' => 'R03DX07','descrizione' => 'Roflumilast','id_cas' => 'cf029'],
      ['id_principio_attivo' => 'R03DX09','descrizione' => 'Mepolizumab','id_cas' => 'cf029'],
      ['id_principio_attivo' => 'R05CA03','descrizione' => 'Guaifenesina','id_cas' => 'cf079'],
      ['id_principio_attivo' => 'R05CB16','descrizione' => 'Mannitol','id_cas' => 'cf079'],
      ['id_principio_attivo' => 'R05DA08','descrizione' => 'Pholcodine','id_cas' => 'cf127'],
      ['id_principio_attivo' => 'R05DB03','descrizione' => 'R05Db03','id_cas' => 'cf127'],
      ['id_principio_attivo' => 'R06AE07','descrizione' => 'Cetirizine','id_cas' => 'cf065'],
      ['id_principio_attivo' => 'R06AX12','descrizione' => 'Terfenadine','id_cas' => 'cf065'],
      ['id_principio_attivo' => 'R06AX13','descrizione' => 'Loratadine','id_cas' => 'cf065'],
      ['id_principio_attivo' => 'R06AX25','descrizione' => 'Mizolastine','id_cas' => 'cf065'],
      ['id_principio_attivo' => 'R06AX27','descrizione' => 'Desloratadine','id_cas' => 'cf065'],
      ['id_principio_attivo' => 'R07AX01','descrizione' => 'Nitric Oxide','id_cas' => 'cf035'],
      ['id_principio_attivo' => 'R07AX02','descrizione' => 'Ivacaftor','id_cas' => 'cf035'],
      ['id_principio_attivo' => 'R07AX30','descrizione' => 'Ivacaftor And Lumacaftor','id_cas' => 'cf035'],
      ['id_principio_attivo' => 'S01AD08','descrizione' => 'Fomivirsen','id_cas' => 'cf057'],
      ['id_principio_attivo' => 'S01AX12','descrizione' => 'Norfloxacin','id_cas' => 'cf057'],
      ['id_principio_attivo' => 'S01BA01','descrizione' => 'Dexamethasone','id_cas' => 'cf007'],
      ['id_principio_attivo' => 'S01BC10','descrizione' => 'Nepafenac','id_cas' => 'cf007'],
      ['id_principio_attivo' => 'S01BC11','descrizione' => 'Bromfenac','id_cas' => 'cf007'],
      ['id_principio_attivo' => 'S01EC04','descrizione' => 'Brinzolamide','id_cas' => 'cf056'],
      ['id_principio_attivo' => 'S01EC54','descrizione' => 'Brinzolamide, Combinations','id_cas' => 'cf056'],
      ['id_principio_attivo' => 'S01ED51','descrizione' => 'Timolol, Combinations','id_cas' => 'cf056'],
      ['id_principio_attivo' => 'S01EE01','descrizione' => 'Latanoprost','id_cas' => 'cf056'],
      ['id_principio_attivo' => 'S01EE03','descrizione' => 'Bimatoprost','id_cas' => 'cf056'],
      ['id_principio_attivo' => 'S01EE04','descrizione' => 'Travoprost','id_cas' => 'cf056'],
      ['id_principio_attivo' => 'S01GX06','descrizione' => 'Emedastine','id_cas' => 'cf073'],
      ['id_principio_attivo' => 'S01GX09','descrizione' => 'Olopatadine','id_cas' => 'cf073'],
      ['id_principio_attivo' => 'S01LA01','descrizione' => 'Verteporfin','id_cas' => 'cf012'],
      ['id_principio_attivo' => 'S01LA03','descrizione' => 'Pegaptanib','id_cas' => 'cf012'],
      ['id_principio_attivo' => 'S01LA04','descrizione' => 'Ranibizumab','id_cas' => 'cf012'],
      ['id_principio_attivo' => 'S01LA05','descrizione' => 'Aflibercept','id_cas' => 'cf012'],
      ['id_principio_attivo' => 'S01XA18','descrizione' => 'Ciclosporin','id_cas' => 'cf030'],
      ['id_principio_attivo' => 'S01XA19','descrizione' => 'Limbal Stems Cells, Autologous','id_cas' => 'cf030'],
      ['id_principio_attivo' => 'S01XA21','descrizione' => 'Mercaptamine','id_cas' => 'cf030'],
      ['id_principio_attivo' => 'S01XA22','descrizione' => 'Ocriplasmin','id_cas' => 'cf030'],
      ['id_principio_attivo' => 'V03AB17','descrizione' => 'Methylthionine','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AB33','descrizione' => 'Hydroxocobalamin','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AB35','descrizione' => 'Sugammadex','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AB37','descrizione' => 'Idarucizumab','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AC02','descrizione' => 'Deferiprone','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AC03','descrizione' => 'Deferasirox','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AE02','descrizione' => 'Sevelamer','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AE05','descrizione' => 'Sucroferric Oxyhydroxide','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AE06','descrizione' => 'Colestilan','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AF02','descrizione' => 'Dexrazoxane','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AF03','descrizione' => 'Calcium Folinate','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AF07','descrizione' => 'Rasburicase','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AF08','descrizione' => 'Palifermin','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AX02','descrizione' => 'Nalfurafine','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V03AX03','descrizione' => 'Cobicistat','id_cas' => 'cf134'],
      ['id_principio_attivo' => 'V04CX','descrizione' => 'Other Diagnostic Agents','id_cas' => 'cf019'],
      ['id_principio_attivo' => 'V08CA02','descrizione' => 'Gadoteric Acid','id_cas' => 'cf104'],
      ['id_principio_attivo' => 'V08CA05','descrizione' => 'Mangafodipir','id_cas' => 'cf104'],
      ['id_principio_attivo' => 'V08CA06','descrizione' => 'Gadoversetamide','id_cas' => 'cf104'],
      ['id_principio_attivo' => 'V08CA08','descrizione' => 'Gadobenic Acid','id_cas' => 'cf104'],
      ['id_principio_attivo' => 'V08CA09','descrizione' => 'Gadobutrol','id_cas' => 'cf104'],
      ['id_principio_attivo' => 'V08CA11','descrizione' => 'Gadofosveset','id_cas' => 'cf104'],
      ['id_principio_attivo' => 'V08DA01','descrizione' => 'Microspheres Of Human Albumin','id_cas' => 'cf105'],
      ['id_principio_attivo' => 'V08DA04','descrizione' => 'Microspheres Of Phospholipids','id_cas' => 'cf105'],
      ['id_principio_attivo' => 'V08DA05','descrizione' => 'Sulfur Hexafluoride','id_cas' => 'cf105'],
      ['id_principio_attivo' => 'V09AB03','descrizione' => 'Iodine Ioflupane (123I)','id_cas' => 'cf128'],
      ['id_principio_attivo' => 'V09AX04','descrizione' => 'Flutemetamol (18F)','id_cas' => 'cf128'],
      ['id_principio_attivo' => 'V09AX05','descrizione' => 'Florbetapir (18F)','id_cas' => 'cf128'],
      ['id_principio_attivo' => 'V09AX06','descrizione' => 'Florbetaben (18F)','id_cas' => 'cf128'],
      ['id_principio_attivo' => 'V09HA03','descrizione' => 'Technetium (99Mtc) Antigranulocyte Antibody','id_cas' => 'cf126'],
      ['id_principio_attivo' => 'V09HA04','descrizione' => 'Technetium (99Mtc) Sulesomab','id_cas' => 'cf126'],
      ['id_principio_attivo' => 'V09IA01','descrizione' => 'Technetium (99Mtc) Anticarcinoembryonicantigen Antibody','id_cas' => 'cf125'],
      ['id_principio_attivo' => 'V09IA02','descrizione' => 'Technetium (99Mtc) Antimelanoma Antibody','id_cas' => 'cf125'],
      ['id_principio_attivo' => 'V09IA05','descrizione' => 'Technetium (99Mtc) Depreotide','id_cas' => 'cf125'],
      ['id_principio_attivo' => 'V09IA09','descrizione' => 'Technetium (99Mtc) Tilmanocept','id_cas' => 'cf125'],
      ['id_principio_attivo' => 'V09IB03','descrizione' => 'Indium (111In) Antiovariumcarcinoma Antibody','id_cas' => 'cf125'],
      ['id_principio_attivo' => 'V09IX04','descrizione' => 'Fludeoxyglucose (18F)','id_cas' => 'cf125'],
      ['id_principio_attivo' => 'V10BX02','descrizione' => 'Samarium (153Sm) Lexidronam','id_cas' => 'cf133'],
      ['id_principio_attivo' => 'V10XX02','descrizione' => 'Ibritumomab Tiuxetan','id_cas' => 'cf037'],
      ['id_principio_attivo' => 'V10XX03','descrizione' => 'Radium (223Ra) Dichloride','id_cas' => 'cf037'],
    ]);
    }
}