<?php

use Illuminate\Database\Seeder;

class LoincTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
 DB::table('tbl_loinc')->insert([
      ['codice_loinc' => '11449-6','loinc_classe' => 'Stato Di Gravidanza','loinc_componente' => 'Gravidanza, Stato','loinc_proprieta' => 'Imp','loinc_temporizzazione' => 'Pt','loinc_sistema' => '^Paziente','loinc_scala' => 'Nom','loinc_metodo' => 'Riportato'],
      ['codice_loinc' => '1751-7','loinc_classe' => 'Albumina','loinc_componente' => 'Albumina','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '17861-6','loinc_classe' => 'Calcio','loinc_componente' => 'Calcio','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '18112-3','loinc_classe' => 'Grado Di Rigurgito Della Valvola Aortica Attraverso Us. Doppler','loinc_componente' => 'Rigurgito, Grado','loinc_proprieta' => 'Arb','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Valvola Aortica','loinc_scala' => 'Ord','loinc_metodo' => 'Eco.Doppler'],
      ['codice_loinc' => '18113-1','loinc_classe' => 'Grado Di Rigurgito Della Valvola Mitrale Attraverso Us. Doppler','loinc_componente' => 'Rigurgito, Grado','loinc_proprieta' => 'Arb','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Valvola Mitrale','loinc_scala' => 'Ord','loinc_metodo' => 'Eco.Doppler'],
      ['codice_loinc' => '18114-9','loinc_classe' => 'Grado Di Rigurgito Della Valvola Polmonare Attraverso Us. Doppler','loinc_componente' => 'Rigurgito, Grado','loinc_proprieta' => 'Arb','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Valvola Polmonare','loinc_scala' => 'Ord','loinc_metodo' => 'Eco.Doppler'],
      ['codice_loinc' => '18115-6','loinc_classe' => 'Grado Di Rigurgito Della Valvola Tricuspide Attraverso Us. Doppler','loinc_componente' => 'Rigurgito, Grado','loinc_proprieta' => 'Arb','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Valvola Tricuspide','loinc_scala' => 'Ord','loinc_metodo' => 'Eco.Doppler'],
      ['codice_loinc' => '2075-0','loinc_classe' => 'Cloruro','loinc_componente' => 'Cloruro','loinc_proprieta' => 'SCnc','loinc_temporizzazione' => 'Pt ','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '2160-0','loinc_classe' => 'Creatinina','loinc_componente' => 'Creatinina','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '24325-3','loinc_classe' => 'Funzionalita\' Epatica','loinc_componente' => 'Funzione Epatica, Panel 2000','loinc_proprieta' => '-','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '27353-2','loinc_classe' => 'Glicemia','loinc_componente' => 'Glucosio Medio Stimato','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sangue','loinc_scala' => 'Qn','loinc_metodo' => 'Stimato Da Emoglobina Gli'],
      ['codice_loinc' => '2774-8','loinc_classe' => 'Fosfato Nel Sangue','loinc_componente' => 'Fosfato','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sangue','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '27975-2','loinc_classe' => 'Tireotropina','loinc_componente' => 'Tireotropina','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '2823-3','loinc_classe' => 'Potassio','loinc_componente' => 'Potassio','loinc_proprieta' => 'SCnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '2951-2','loinc_classe' => 'Sodio','loinc_componente' => 'Sodio','loinc_proprieta' => 'SCnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '3026-2','loinc_classe' => 'Tiroxina (T4)','loinc_componente' => 'Tiroxina','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '30341-2','loinc_classe' => 'Velocita\' Di Sedimentazione Eritrocitaria','loinc_componente' => 'Eritrociti, Velocita\' Di Sedimentazione','loinc_proprieta' => 'Vel','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sangue','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '3053-6','loinc_classe' => 'Triiodotironina (T3)','loinc_componente' => 'Triiodotironina','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '30934-4','loinc_classe' => 'Peptide Natriuretico B','loinc_componente' => 'Peptide Natriuretico.B','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '3094-0','loinc_classe' => 'Azoto Ureico','loinc_componente' => 'Azoto Ureico','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '32431-9','loinc_classe' => 'Osservazioni Fisiche Della Palpebra','loinc_componente' => 'Osservazioni Fisiche','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Occhio, Palpebra','loinc_scala' => 'Nom','loinc_metodo' => 'Osservato'],
      ['codice_loinc' => '32447-5','loinc_classe' => 'Osservazione Fisica Del Fegato','loinc_componente' => 'Osservazioni Fisiche','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Fegato','loinc_scala' => 'Nom','loinc_metodo' => '-'],
      ['codice_loinc' => '32449-1','loinc_classe' => 'Osservazione Fisica Del Polmone','loinc_componente' => 'Osservazioni Fisiche','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Polmone','loinc_scala' => 'Nom','loinc_metodo' => '-'],
      ['codice_loinc' => '32479-8','loinc_classe' => 'Osservazione Fisica Alla Tiroide','loinc_componente' => 'Osservazioni Fisiche','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Tiroide','loinc_scala' => 'Nom','loinc_metodo' => 'Osservato'],
      ['codice_loinc' => '32698-3','loinc_classe' => 'Magnesio','loinc_componente' => 'Magnesio.Libero','loinc_proprieta' => 'Mcnc','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Siero/Plasma','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '33455-7','loinc_classe' => 'Aspetto Di Espettorato','loinc_componente' => 'Aspetto','loinc_proprieta' => 'Asp','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Espettorato','loinc_scala' => 'Nom','loinc_metodo' => ''],
      ['codice_loinc' => '37221-9','loinc_classe' => 'Fistola','loinc_componente' => 'Sezione multipla per fistola','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'XXX','loinc_scala' => 'Doc','loinc_metodo' => 'CT'],
      ['codice_loinc' => '39107-8','loinc_classe' => 'Colore Della Pelle','loinc_componente' => 'Colore','loinc_proprieta' => 'Tipo','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Pelle','loinc_scala' => 'Nom','loinc_metodo' => '-'],
      ['codice_loinc' => '42160-2','loinc_classe' => 'Shunt X-ray','loinc_componente' => 'Visione','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Shunt','loinc_scala' => 'Doc','loinc_metodo' => 'X-ray'],
      ['codice_loinc' => '44968-6','loinc_classe' => 'Temperatura Di Palpazione Della Pelle','loinc_componente' => 'Temperatura','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Pelle','loinc_scala' => 'Ord','loinc_metodo' => 'Palpazione'],
      ['codice_loinc' => '45644-2','loinc_classe' => 'Ipotensione','loinc_componente' => 'Ipotensione','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Paziente','loinc_scala' => 'Ord','loinc_metodo' => 'Mds'],
      ['codice_loinc' => '55407-1','loinc_classe' => 'Gravita\' Edemi Della Caviglia','loinc_componente' => 'Edemi, Gravita\'','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Caviglia','loinc_scala' => 'Ord','loinc_metodo' => '-'],
      ['codice_loinc' => '66618-0','loinc_classe' => 'Ipertensione Polmonare','loinc_componente' => 'Ipertensione Polmonare','loinc_proprieta' => 'Hx','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Paziente','loinc_scala' => 'Ord','loinc_metodo' => 'Riportato'],
      ['codice_loinc' => '69428-1','loinc_classe' => 'Distensione Venosa Giugulare','loinc_componente' => 'Distensione Venosa Giugulare','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Paziente','loinc_scala' => 'Ord','loinc_metodo' => '-'],
      ['codice_loinc' => '69742-5','loinc_classe' => 'Pannello Cbc','loinc_componente' => 'Cbc W, Panel Differenziale, Metodo Non Specificato','loinc_proprieta' => '-','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sangue','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '77701-1','loinc_classe' => 'Tremore','loinc_componente' => 'Tremore, Scala','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Paziente','loinc_scala' => 'Ord','loinc_metodo' => 'Updrs'],
      ['codice_loinc' => '80271-0','loinc_classe' => 'Osservazione Fisica Dell\'Addome','loinc_componente' => 'Osservazioni Fisiche','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Addome','loinc_scala' => 'Nom','loinc_metodo' => 'Palpazione'],
      ['codice_loinc' => '80276-9','loinc_classe' => 'Toni Cardiaci','loinc_componente' => 'Toni Cardiaci','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Cuore','loinc_scala' => 'Nom','loinc_metodo' => '-'],
      ['codice_loinc' => '80278-5','loinc_classe' => 'Soffio Cardiaco, Grado','loinc_componente' => 'Soffio, Grado','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Cuore','loinc_scala' => 'Nom','loinc_metodo' => 'Auscultazione'],
      ['codice_loinc' => '80280-1','loinc_classe' => 'Soffio Al Cuore, Intensita\'','loinc_componente' => 'Soffio, Intensita\'','loinc_proprieta' => 'Tipo','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Cuore','loinc_scala' => 'Nom','loinc_metodo' => 'Auscultazione'],
      ['codice_loinc' => '80281-9','loinc_classe' => 'Soffio Al Cuore, Contrazione','loinc_componente' => 'Soffio, Contrazione','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Cuore','loinc_scala' => 'Nom','loinc_metodo' => 'Auscultazione'],
      ['codice_loinc' => '80282-7','loinc_classe' => 'Soffio Localizzato Con Auscultazione','loinc_componente' => 'Soffio, Localizzato','loinc_proprieta' => 'Anat','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Paziente','loinc_scala' => 'Nom','loinc_metodo' => 'Auscultazione'],
      ['codice_loinc' => '80319-7','loinc_classe' => 'Rumori Respiratori Con Auscultazione','loinc_componente' => 'Rumori Respiratori','loinc_proprieta' => 'Find','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sistema Respiratorio','loinc_scala' => 'Nom','loinc_metodo' => 'Auscultazione'],
      ['codice_loinc' => '8462-4','loinc_classe' => 'Pressione sanguigna diastolica','loinc_componente' => 'diastolica intravascolare','loinc_proprieta' => 'Pressione','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sistema Arterioso','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '8480-6','loinc_classe' => 'Pressione sanguigna sistolica','loinc_componente' => 'sistolica intravascolare','loinc_proprieta' => 'Pressione','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Sistema Arterioso','loinc_scala' => 'Qn','loinc_metodo' => '-'],
      ['codice_loinc' => '8594-4','loinc_classe' => 'Pulsazione Alla Vena Giugulare','loinc_componente' => 'Onda V, Ampiezza','loinc_proprieta' => 'Pres','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Vena Giugulare','loinc_scala' => 'Ord','loinc_metodo' => 'Visivo'],
      ['codice_loinc' => '8699-1','loinc_classe' => 'Osservazioni Fisiche Occhio','loinc_componente' => 'Osservazioni Fisiche','loinc_proprieta' => 'Osservazio','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Occhio','loinc_scala' => 'Nom','loinc_metodo' => 'Osservato'],
      ['codice_loinc' => '8866-6','loinc_classe' => 'Qualita\' Pulsazione Arteriosa Con La Palpazione','loinc_componente' => 'Pulsazione Arteriosa, Qualita\'','loinc_proprieta' => 'Tipo','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Xxx','loinc_scala' => 'Nom','loinc_metodo' => 'Palpazione'],
      ['codice_loinc' => '8890-6','loinc_classe' => 'Frequenza Cardiaca','loinc_componente' => 'Frequenza Cardiaca','loinc_proprieta' => 'Nrat','loinc_temporizzazione' => 'Pt','loinc_sistema' => 'Apice Cardiaco','loinc_scala' => 'Qn','loinc_metodo' => 'Auscultazione'],
      ['codice_loinc' => 'LL1654-4','loinc_classe' => 'Etnia','loinc_componente' => 'Etnia','loinc_proprieta' => '-','loinc_temporizzazione' => '-','loinc_sistema' => '-','loinc_scala' => '-','loinc_metodo' => '-'],
      ['codice_loinc' => 'X00015-0','loinc_classe' => 'Tachicardia','loinc_componente' => 'Battito Cardiaco','loinc_proprieta' => 'Numero','loinc_temporizzazione' => '-','loinc_sistema' => 'Paziente','loinc_scala' => 'Ordin','loinc_metodo' => '-'],
      ['codice_loinc' => 'X00022-6','loinc_classe' => 'Pressione Differenziale','loinc_componente' => 'Pannello Della Pressione Differenziale','loinc_proprieta' => 'Numero','loinc_temporizzazione' => '-','loinc_sistema' => 'Paziente','loinc_scala' => 'Ordin','loinc_metodo' => 'Sfigmomanometro'],
      ['codice_loinc' => 'X00025-9','loinc_classe' => 'Pressione Sanguigna','loinc_componente' => 'Pannello Della Pressione Sanguigna','loinc_proprieta' => 'Numero','loinc_temporizzazione' => '-','loinc_sistema' => 'Paziente','loinc_scala' => 'Ordin','loinc_metodo' => 'Sfigmomanometro'],
      ['codice_loinc' => 'X00027-5','loinc_classe' => 'Schiocco D\'Apertura','loinc_componente' => 'Rumore Della Valvola Mitrale','loinc_proprieta' => '-','loinc_temporizzazione' => '-','loinc_sistema' => 'Cuore','loinc_scala' => '-','loinc_metodo' => 'Auscultazione'],
    ]);
    }
}
