INSERT INTO `ATC_Sottogruppo_Terapeutico_F` (`id_sottogruppoTF`, `Descrizione`, `ID_Gruppo_Terapeutico`, `Codice_Gruppo_Teraputico`) VALUES
("A01A", "Stomatological preparations\r", "A01", "A"),
("A02A", "Antacids\r", "A02", "A"),
("A02B", "Drugs for peptic ulcer and gastro-oesophageal reflux disease (gord)\r", "A02", "B"),
("A02X", "Other drugs for acid related disorders\r", "A02", "X"),
("A03A", "Drugs for functional gastrointestinal disorders\r", "A03", "A"),
("A03B", "Belladonna and derivatives, plain\r", "A03", "B"),
("A03C", "Antispasmodics in combination with psycholeptics\r", "A03", "C"),
("A03D", "Antispasmodics in combination with analgesics\r", "A03", "D"),
("A03E", "Antispasmodics and anticholinergics in combination with other drugs\r", "A03", "E"),
("A03F", "Propulsives\r", "A03", "F"),
("A04A", "Antiemetics and antinauseants\r", "A04", "A"),
("A05A", "Bile therapy\r", "A05", "A"),
("A05B", "Liver therapy, lipotropics\r", "A05", "B"),
("A05C", "Drugs for bile therapy and lipotropics in combination\r", "A05", "C"),
("A06A", "Drugs for constipation\r", "A06", "A"),
("A07A", "Intestinal antiinfectives\r", "A07", "A"),
("A07B", "Intestinal adsorbents\r", "A07", "B"),
("A07C", "Electrolytes with carbohydrates\r", "A07", "C"),
("A07D", "Antipropulsives\r", "A07", "D"),
("A07E", "Intestinal antiinflammatory agents\r", "A07", "E"),
("A07F", "Antidiarrheal microorganisms\r", "A07", "F"),
("A07X", "Other antidiarrheals\r", "A07", "X"),
("A08A", "Antiobesity preparations, excl. diet products\r", "A08", "A"),
("A09A", "Digestives, incl. enzymes\r", "A09", "A"),
("A10A", "Insulins and analogues\r", "A10", "A"),
("A10B", "Blood glucose lowering drugs, excl. insulins\r", "A10", "B"),
("A10X", "Other drugs used in diabetes\r", "A10", "X"),
("A11A", "Multivitamins, combinations\r", "A11", "A"),
("A11B", "Multivitamins, plain\r", "A11", "B"),
("A11C", "Vitamin a and d, incl. combinations of the two\r", "A11", "C"),
("A11D", "Vitamin b1, plain and in combination with vitamin b6 and b12\r", "A11", "D"),
("A11E", "Vitamin b-complex, incl. combinations\r", "A11", "E"),
("A11G", "Ascorbic acid (vitamin c), incl. combinations\r", "A11", "G"),
("A11H", "Other plain vitamin preparations\r", "A11", "H"),
("A11J", "Other vitamin products, combinations\r", "A11", "J"),
("A12A", "Calcium\r", "A12", "A"),
("A12B", "Potassium\r", "A12", "B"),
("A12C", "Other mineral supplements\r", "A12", "C"),
("A13A", "Tonics\r", "A13", "A"),
("A14A", "Anabolic steroids\r", "A14", "A"),
("A14B", "Other anabolic agents\r", "A14", "B"),
("A16A", "Other alimentary tract and metabolism products\r", "A16", "A"),
("B01A", "Antithrombotic agents\r", "B01", "A"),
("B02A", "Antifibrinolytics\r", "B02", "A"),
("B02B", "Vitamin k and other hemostatics\r", "B02", "B"),
("B03A", "Iron preparations\r", "B03", "A"),
("B03B", "Vitamin b12 and folic acid\r", "B03", "B"),
("B03X", "Other antianemic preparations\r", "B03", "X"),
("B05A", "Blood and related products\r", "B05", "A"),
("B05B", "I.v. solutions\r", "B05", "B"),
("B05C", "Irrigating solutions\r", "B05", "C"),
("B05D", "Peritoneal dialytics\r", "B05", "D"),
("B05X", "I.v. solution additives\r", "B05", "X"),
("B05Z", "Hemodialytics and hemofiltrates\r", "B05", "Z"),
("B06A", "Other hematological agents\r", "B06", "A"),
("C01A", "Cardiac glycosides\r", "C01", "A"),
("C01B", "Antiarrhythmics, class i and iii\r", "C01", "B"),
("C01C", "Cardiac stimulants excl. cardiac glycosides\r", "C01", "C"),
("C01D", "Vasodilators used in cardiac diseases\r", "C01", "D"),
("C01E", "Other cardiac preparations\r", "C01", "E"),
("C02A", "Antiadrenergic agents, centrally acting\r", "C02", "A"),
("C02B", "Antiadrenergic agents, ganglion-blocking\r", "C02", "B"),
("C02C", "Antiadrenergic agents, peripherally acting\r", "C02", "C"),
("C02D", "Arteriolar smooth muscle, agents acting on\r", "C02", "D"),
("C02K", "Other antihypertensives\r", "C02", "K"),
("C02L", "Antihypertensives and diuretics in combination\r", "C02", "L"),
("C02N", "Combinations of antihypertensives in atc-gr. c02\r", "C02", "N"),
("C03A", "Low-ceiling diuretics, thiazides\r", "C03", "A"),
("C03B", "Low-ceiling diuretics, excl. thiazides\r", "C03", "B"),
("C03C", "High-ceiling diuretics\r", "C03", "C"),
("C03D", "Potassium-sparing agents\r", "C03", "D"),
("C03E", "Diuretics and potassium-sparing agents in combination\r", "C03", "E"),
("C03X", "Other diuretics\r", "C03", "X"),
("C04A", "Peripheral vasodilators\r", "C04", "A"),
("C05A", "Agents for treatment of hemorrhoids and anal fissures for topical use\r", "C05", "A"),
("C05B", "Antivaricose therapy\r", "C05", "B"),
("C05C", "Capillary stabilizing agents\r", "C05", "C"),
("C07A", "Beta blocking agents\r", "C07", "A"),
("C07B", "Beta blocking agents and thiazides\r", "C07", "B"),
("C07C", "Beta blocking agents and other diuretics\r", "C07", "C"),
("C07D", "Beta blocking agents, thiazides and other diuretics\r", "C07", "D"),
("C07E", "Beta blocking agents and vasodilators\r", "C07", "E"),
("C07F", "Beta blocking agents and other antihypertensives\r", "C07", "F"),
("C08C", "Selective calcium channel blockers with mainly vascular effects\r", "C08", "C"),
("C08D", "Selective calcium channel blockers with direct cardiac effects\r", "C08", "D"),
("C08E", "Non-selective calcium channel blockers\r", "C08", "E"),
("C08G", "Calcium channel blockers and diuretics\r", "C08", "G"),
("C09A", "Ace inhibitors, plain\r", "C09", "A"),
("C09B", "Ace inhibitors, combinations\r", "C09", "B"),
("C09C", "Angiotensin ii antagonists, plain\r", "C09", "C"),
("C09D", "Angiotensin ii antagonists, combinations\r", "C09", "D"),
("C09X", "Other agents acting on the renin-angiotensin system\r", "C09", "X"),
("C10A", "Lipid modifying agents, plain\r", "C10", "A"),
("C10B", "Lipid modifying agents, combinations\r", "C10", "B"),
("D01A", "Antifungals for topical use\r", "D01", "A"),
("D01B", "Antifungals for systemic use\r", "D01", "B"),
("D02A", "Emollients and protectives\r", "D02", "A"),
("D02B", "Protectives against uv-radiation\r", "D02", "B"),
("D03A", "Cicatrizants\r", "D03", "A"),
("D03B", "Enzymes\r", "D03", "B"),
("D04A", "Antipruritics, incl. antihistamines, anesthetics, etc.\r", "D04", "A"),
("D05A", "Antipsoriatics for topical use\r", "D05", "A"),
("D05B", "Antipsoriatics for systemic use\r", "D05", "B"),
("D06A", "Antibiotics for topical use\r", "D06", "A"),
("D06B", "Chemotherapeutics for topical use\r", "D06", "B"),
("D06C", "Antibiotics and chemotherapeutics, combinations\r", "D06", "C"),
("D07A", "Corticosteroids, plain\r", "D07", "A"),
("D07B", "Corticosteroids, combinations with antiseptics\r", "D07", "B"),
("D07C", "Corticosteroids, combinations with antibiotics\r", "D07", "C"),
("D07X", "Corticosteroids, other combinations\r", "D07", "X"),
("D08A", "Antiseptics and disinfectants\r", "D08", "A"),
("D09A", "Medicated dressings\r", "D09", "A"),
("D10A", "Anti-acne preparations for topical use\r", "D10", "A"),
("D10B", "Anti-acne preparations for systemic use\r", "D10", "B"),
("D11A", "Other dermatological preparations\r", "D11", "A"),
("G01A", "Antiinfectives and antiseptics, excl. combinations with corticosteroids\r", "G01", "A"),
("G01B", "Antiinfectives/antiseptics in combination with corticosteroids\r", "G01", "B"),
("G02A", "Uterotonics\r", "G02", "A"),
("G02B", "Contraceptives for topical use\r", "G02", "B"),
("G02C", "Other gynecologicals\r", "G02", "C"),
("G03A", "Hormonal contraceptives for systemic use\r", "G03", "A"),
("G03B", "Androgens\r", "G03", "B"),
("G03C", "Estrogens\r", "G03", "C"),
("G03D", "Progestogens\r", "G03", "D"),
("G03E", "Androgens and female sex hormones in combination\r", "G03", "E"),
("G03F", "Progestogens and estrogens in combination\r", "G03", "F"),
("G03G", "Gonadotropins and other ovulation stimulants\r", "G03", "G"),
("G03H", "Antiandrogens\r", "G03", "H"),
("G03X", "Other sex hormones and modulators of the genital system\r", "G03", "X"),
("G04B", "Urologicals\r", "G04", "B"),
("G04C", "Drugs used in benign prostatic hypertrophy\r", "G04", "C"),
("H01A", "Anterior pituitary lobe hormones and analogues\r", "H01", "A"),
("H01B", "Posterior pituitary lobe hormones\r", "H01", "B"),
("H01C", "Hypothalamic hormones\r", "H01", "C"),
("H02A", "Corticosteroids for systemic use, plain\r", "H02", "A"),
("H02B", "Corticosteroids for systemic use, combinations\r", "H02", "B"),
("H02C", "Antiadrenal preparations\r", "H02", "C"),
("H03A", "Thyroid preparations\r", "H03", "A"),
("H03B", "Antithyroid preparations\r", "H03", "B"),
("H03C", "Iodine therapy\r", "H03", "C"),
("H04A", "Glycogenolytic hormones\r", "H04", "A"),
("H05A", "Parathyroid hormones and analogues\r", "H05", "A"),
("H05B", "Anti-parathyroid agents\r", "H05", "B"),
("J01A", "Tetracyclines\r", "J01", "A"),
("J01B", "Amphenicols\r", "J01", "B"),
("J01C", "Beta-lactam antibacterials, penicillins\r", "J01", "C"),
("J01D", "Other beta-lactam antibacterials\r", "J01", "D"),
("J01E", "Sulfonamides and trimethoprim\r", "J01", "E"),
("J01F", "Macrolides, lincosamides and streptogramins\r", "J01", "F"),
("J01G", "Aminoglycoside antibacterials\r", "J01", "G"),
("J01M", "Quinolone antibacterials\r", "J01", "M"),
("J01R", "Combinations of antibacterials\r", "J01", "R"),
("J01X", "Other antibacterials\r", "J01", "X"),
("J02A", "Antimycotics for systemic use\r", "J02", "A"),
("J04A", "Drugs for treatment of tuberculosis\r", "J04", "A"),
("J04B", "Drugs for treatment of lepra\r", "J04", "B"),
("J05A", "Direct acting antivirals\r", "J05", "A"),
("J06A", "Immune sera\r", "J06", "A"),
("J06B", "Immunoglobulins\r", "J06", "B"),
("J07A", "Bacterial vaccines\r", "J07", "A"),
("J07B", "Viral vaccines\r", "J07", "B"),
("J07C", "Bacterial and viral vaccines, combined\r", "J07", "C"),
("J07X", "Other vaccines\r", "J07", "X"),
("L01A", "Alkylating agents\r", "L01", "A"),
("L01B", "Antimetabolites\r", "L01", "B"),
("L01C", "Plant alkaloids and other natural products\r", "L01", "C"),
("L01D", "Cytotoxic antibiotics and related substances\r", "L01", "D"),
("L01X", "Other antineoplastic agents\r", "L01", "X"),
("L02A", "Hormones and related agents\r", "L02", "A"),
("L02B", "Hormone antagonists and related agents\r", "L02", "B"),
("L03A", "Immunostimulants\r", "L03", "A"),
("L04A", "Immunosuppressants\r", "L04", "A"),
("M01A", "Antiinflammatory and antirheumatic products, non-steroids\r", "M01", "A"),
("M01B", "Antiinflammatory/antirheumatic agents in combination\r", "M01", "B"),
("M01C", "Specific antirheumatic agents\r", "M01", "C"),
("M02A", "Topical products for joint and muscular pain\r", "M02", "A"),
("M03A", "Muscle relaxants, peripherally acting agents\r", "M03", "A"),
("M03B", "Muscle relaxants, centrally acting agents\r", "M03", "B"),
("M03C", "Muscle relaxants, directly acting agents\r", "M03", "C"),
("M04A", "Antigout preparations\r", "M04", "A"),
("M05B", "Drugs affecting bone structure and mineralization\r", "M05", "B"),
("M09A", "Other drugs for disorders of the musculo-skeletal system\r", "M09", "A"),
("N01A", "Anesthetics, general\r", "N01", "A"),
("N01B", "Anesthetics, local\r", "N01", "B"),
("N02A", "Opioids\r", "N02", "A"),
("N02B", "Other analgesics and antipyretics\r", "N02", "B"),
("N02C", "Antimigraine preparations\r", "N02", "C"),
("N03A", "Antiepileptics\r", "N03", "A"),
("N04A", "Anticholinergic agents\r", "N04", "A"),
("N04B", "Dopaminergic agents\r", "N04", "B"),
("N05A", "Antipsychotics\r", "N05", "A"),
("N05B", "Anxiolytics\r", "N05", "B"),
("N05C", "Hypnotics and sedatives\r", "N05", "C"),
("N06A", "Antidepressants\r", "N06", "A"),
("N06B", "Psychostimulants, agents used for adhd and nootropics\r", "N06", "B"),
("N06C", "Psycholeptics and psychoanaleptics in combination\r", "N06", "C"),
("N06D", "Anti-dementia drugs\r", "N06", "D"),
("N07A", "Parasympathomimetics\r", "N07", "A"),
("N07B", "Drugs used in addictive disorders\r", "N07", "B"),
("N07C", "Antivertigo preparations\r", "N07", "C"),
("N07X", "Other nervous system drugs\r", "N07", "X"),
("P01A", "Agents against amoebiasis and other protozoal diseases\r", "P01", "A"),
("P01B", "Antimalarials\r", "P01", "B"),
("P01C", "Agents against leishmaniasis and trypanosomiasis\r", "P01", "C"),
("P02B", "Antitrematodals\r", "P02", "B"),
("P02C", "Antinematodal agents\r", "P02", "C"),
("P02D", "Anticestodals\r", "P02", "D"),
("P03A", "Ectoparasiticides, incl. scabicides\r", "P03", "A"),
("P03B", "Insecticides and repellents\r", "P03", "B"),
("R01A", "Decongestants and other nasal preparations for topical use\r", "R01", "A"),
("R01B", "Nasal decongestants for systemic use\r", "R01", "B"),
("R02A", "Throat preparations\r", "R02", "A"),
("R03A", "Adrenergics, inhalants\r", "R03", "A"),
("R03B", "Other drugs for obstructive airway diseases, inhalants\r", "R03", "B"),
("R03C", "Adrenergics for systemic use\r", "R03", "C"),
("R03D", "Other systemic drugs for obstructive airway diseases\r", "R03", "D"),
("R05C", "Expectorants, excl. combinations with cough suppressants\r", "R05", "C"),
("R05D", "Cough suppressants, excl. combinations with expectorants\r", "R05", "D"),
("R05F", "Cough suppressants and expectorants, combinations\r", "R05", "F"),
("R05X", "Other cold preparations\r", "R05", "X"),
("R06A", "Antihistamines for systemic use\r", "R06", "A"),
("R07A", "Other respiratory system products\r", "R07", "A"),
("S01A", "Antiinfectives\r", "S01", "A"),
("S01B", "Antiinflammatory agents\r", "S01", "B"),
("S01C", "Antiinflammatory agents and antiinfectives in combination\r", "S01", "C"),
("S01E", "Antiglaucoma preparations and miotics\r", "S01", "E"),
("S01F", "Mydriatics and cycloplegics\r", "S01", "F"),
("S01G", "Decongestants and antiallergics\r", "S01", "G"),
("S01H", "Local anesthetics\r", "S01", "H"),
("S01J", "Diagnostic agents\r", "S01", "J"),
("S01K", "Surgical aids\r", "S01", "K"),
("S01L", "Ocular vascular disorder agents\r", "S01", "L"),
("S01X", "Other ophthalmologicals\r", "S01", "X"),
("S02A", "Antiinfectives\r", "S02", "A"),
("S02B", "Corticosteroids\r", "S02", "B"),
("S02C", "Corticosteroids and antiinfectives in combination\r", "S02", "C"),
("S02D", "Other otologicals\r", "S02", "D"),
("S03A", "Antiinfectives\r", "S03", "A"),
("S03B", "Corticosteroids\r", "S03", "B"),
("S03C", "Corticosteroids and antiinfectives in combination\r", "S03", "C"),
("S03D", "Other ophthalmological and otological preparations\r", "S03", "D"),
("V01A", "Allergens\r", "V01", "A"),
("V03A", "All other therapeutic products\r", "V03", "A"),
("V04B", "Urine tests\r", "V04", "B"),
("V04C", "Other diagnostic agents\r", "V04", "C"),
("V06A", "Diet formulations for treatment of obesity\r", "V06", "A"),
("V06B", "Protein supplements\r", "V06", "B"),
("V06C", "Infant formulas\r", "V06", "C"),
("V06D", "Other nutrients\r", "V06", "D"),
("V07A", "All other non-therapeutic products\r", "V07", "A"),
("V08A", "X-ray contrast media, iodinated\r", "V08", "A"),
("V08B", "X-ray contrast media, non-iodinated\r", "V08", "B"),
("V08C", "Magnetic resonance imaging contrast media\r", "V08", "C"),
("V08D", "Ultrasound contrast media\r", "V08", "D"),
("V09A", "Central nervous system\r", "V09", "A"),
("V09B", "Skeleton\r", "V09", "B"),
("V09C", "Renal system\r", "V09", "C"),
("V09D", "Hepatic and reticulo endothelial system\r", "V09", "D"),
("V09E", "Respiratory system\r", "V09", "E"),
("V09F", "Thyroid\r", "V09", "F"),
("V09G", "Cardiovascular system\r", "V09", "G"),
("V09H", "Inflammation and infection detection\r", "V09", "H"),
("V09I", "Tumour detection\r", "V09", "I"),
("V09X", "Other diagnostic radiopharmaceuticals\r", "V09", "X"),
("V10A", "Antiinflammatory agents\r", "V10", "A"),
("V10B", "Pain palliation (bone seeking agents)\r", "V10", "B"),
("V10X", "Other therapeutic radiopharmaceuticals\r", "V10", "X");