INSERT INTO `ATC_Gruppo_Terapeutico_P` (`Codice_Gruppo_Teraputico`, `Descrizione`, `ID_Gruppo_Anatomico`, `Codice_GTP`) VALUES
("A01", "Stomatological preparations\r", "A", "01"),
("A02", "Drugs for acid related disorders\r", "A", "02"),
("A03", "Drugs for functional gastrointestinal disorders\r", "A", "03"),
("A04", "Antiemetics and antinauseants\r", "A", "04"),
("A05", "Bile and liver therapy\r", "A", "05"),
("A06", "Drugs for constipation\r", "A", "06"),
("A07", "Antidiarrheals, intestinal antiinflammatory/antiinfective agents\r", "A", "07"),
("A08", "Antiobesity preparations, excl. diet products\r", "A", "08"),
("A09", "Digestives, incl. enzymes\r", "A", "09"),
("A10", "Drugs used in diabetes\r", "A", "10"),
("A11", "Vitamins\r", "A", "11"),
("A12", "Mineral supplements\r", "A", "12"),
("A13", "Tonics\r", "A", "13"),
("A14", "Anabolic agents for systemic use\r", "A", "14"),
("A15", "Appetite stimulants\r", "A", "15"),
("A16", "Other alimentary tract and metabolism products\r", "A", "16"),
("B01", "Antithrombotic agents\r", "B", "01"),
("B02", "Antihemorrhagics\r", "B", "02"),
("B03", "Antianemic preparations\r", "B", "03"),
("B05", "Blood substitutes and perfusion solutions\r", "B", "05"),
("B06", "Other hematological agents\r", "B", "06"),
("C01", "Cardiac therapy\r", "C", "01"),
("C02", "Antihypertensives\r", "C", "02"),
("C03", "Diuretics\r", "C", "03"),
("C04", "Peripheral vasodilators\r", "C", "04"),
("C05", "Vasoprotectives\r", "C", "05"),
("C07", "Beta blocking agents\r", "C", "07"),
("C08", "Calcium channel blockers\r", "C", "08"),
("C09", "Agents acting on the renin-angiotensin system\r", "C", "09"),
("C10", "Lipid modifying agents\r", "C", "10"),
("D01", "Antifungals for dermatological use\r", "D", "01"),
("D02", "Emollients and protectives\r", "D", "02"),
("D03", "Preparations for treatment of wounds and ulcers\r", "D", "03"),
("D04", "Antipruritics, incl. antihistamines, anesthetics, etc.\r", "D", "04"),
("D05", "Antipsoriatics\r", "D", "05"),
("D06", "Antibiotics and chemotherapeutics for dermatological use\r", "D", "06"),
("D07", "Corticosteroids, dermatological preparations\r", "D", "07"),
("D08", "Antiseptics and disinfectants\r", "D", "08"),
("D09", "Medicated dressings\r", "D", "09"),
("D10", "Anti-acne preparations\r", "D", "10"),
("D11", "Other dermatological preparations\r", "D", "11"),
("G01", "Gynecological antiinfectives and antiseptics\r", "G", "01"),
("G02", "Other gynecologicals\r", "G", "02"),
("G03", "Sex hormones and modulators of the genital system\r", "G", "03"),
("G04", "Urologicals\r", "G", "04"),
("H01", "Pituitary and hypothalamic hormones and analogues\r", "H", "01"),
("H02", "Corticosteroids for systemic use\r", "H", "02"),
("H03", "Thyroid therapy\r", "H", "03"),
("H04", "Pancreatic hormones\r", "H", "04"),
("H05", "Calcium homeostasis\r", "H", "05"),
("J01", "Antibacterials for systemic use\r", "J", "01"),
("J02", "Antimycotics for systemic use\r", "J", "02"),
("J04", "Antimycobacterials\r", "J", "04"),
("J05", "Antivirals for systemic use\r", "J", "05"),
("J06", "Immune sera and immunoglobulins\r", "J", "06"),
("J07", "Vaccines\r", "J", "07"),
("L01", "Antineoplastic agents\r", "L", "01"),
("L02", "Endocrine therapy\r", "L", "02"),
("L03", "Immunostimulants\r", "L", "03"),
("L04", "Immunosuppressants\r", "L", "04"),
("M01", "Antiinflammatory and antirheumatic products\r", "M", "01"),
("M02", "Topical products for joint and muscular pain\r", "M", "02"),
("M03", "Muscle relaxants\r", "M", "03"),
("M04", "Antigout preparations\r", "M", "04"),
("M05", "Drugs for treatment of bone diseases\r", "M", "05"),
("M09", "Other drugs for disorders of the musculo-skeletal system\r", "M", "09"),
("N01", "Anesthetics\r", "N", "01"),
("N02", "Analgesics\r", "N", "02"),
("N03", "Antiepileptics\r", "N", "03"),
("N04", "Anti-parkinson drugs\r", "N", "04"),
("N05", "Psycholeptics\r", "N", "05"),
("N06", "Psychoanaleptics\r", "N", "06"),
("N07", "Other nervous system drugs\r", "N", "07"),
("P01", "Antiprotozoals\r", "P", "01"),
("P02", "Anthelmintics\r", "P", "02"),
("P03", "Ectoparasiticides, incl. scabicides, insecticides and repellents\r", "P", "03"),
("R01", "Nasal preparations\r", "R", "01"),
("R02", "Throat preparations\r", "R", "02"),
("R03", "Drugs for obstructive airway diseases\r", "R", "03"),
("R05", "Cough and cold preparations\r", "R", "05"),
("R06", "Antihistamines for systemic use\r", "R", "06"),
("R07", "Other respiratory system products\r", "R", "07"),
("S01", "Ophthalmologicals\r", "S", "01"),
("S02", "Otologicals\r", "S", "02"),
("S03", "Ophthalmological and otological preparations\r", "S", "03"),
("V01", "Allergens\r", "V", "01"),
("V03", "All other therapeutic products\r", "V", "03"),
("V04", "Diagnostic agents\r", "V", "04"),
("V06", "General nutrients\r", "V", "06"),
("V07", "All other non-therapeutic products\r", "V", "07"),
("V08", "Contrast media\r", "V", "08"),
("V09", "Diagnostic radiopharmaceuticals\r", "V", "09"),
("V10", "Therapeutic radiopharmaceuticals\r", "V", "10"),
("V20", "Surgical dressings\r", "V", "20");