INSERT INTO `tbl_Gruppo_Anatomico_P` (`ID_Gruppo_Anatomico`, `Descrizione`) VALUES
("A", "Alimentary tract and metabolism\r"),
("B", "Blood and blood forming organs\r"),
("C", "Cardiovascular system\r"),
("D", "Dermatologicals\r"),
("G", "Genito urinary system and sex hormones\r"),
("H", "Systemic hormonal preparations, excl. sex hormones and insulins\r"),
("J", "Antiinfectives for systemic use\r"),
("L", "Antineoplastic and immunomodulating agents\r"),
("M", "Musculo-skeletal system\r"),
("N", "Nervous system\r"),
("P", "Antiparasitic products, insecticides and repellents\r"),
("R", "Respiratory system\r"),
("S", "Sensory organs\r"),
("V", "Various\r");