INSERT INTO `tbl_icd9_bloc_diag_codici` (`codice_blocco`, `blocco_cod_descrizione`, `codice_gruppo`) VALUES
('a1','Malattie Infettive Intestinali\r','a'),
('a2','Tubercolosi\r','a'),
('a3','Malattie Batteriche Trasmesse Da Animali\r','a'),
('a4','Altre Malattie Batteriche\r','a'),
('a5','Infezione Da Virus Della Immunodeficienza Umana (Hiv)\r','a'),
('a6','Poliomielite Ed Altre Malattie Virali Del Sistema Nervoso Centrale Non Trasmesse Da Artropodi\r','a'),
('a7','Malattie Virali Con Esantema\r','a'),
('a8','Malattie Virali Da Artropodi\r','a'),
('a9','Altre Malattie Da Virus E Clamidia\r','a'),
('a10','Rickettsiosi Ed Altre Malattie Trasmesse Da Artropodi\r','a'),
('a11','Sifilide Ed Altre Malattie Veneree\r','a'),
('a12','Altre Malattie Da Spirochete\r','a'),
('a13','Micosi\r','a'),
('a14','Elmintiasi\r','a'),
('a15','Altre Malattie Infettive E Parassitarie\r','a'),
('a16','Postumi Di Malattie Infettive E Parassitarie\r','a'),
('b1','Tumori Maligni Delle Labbra, Della Cavita Orale, Della Faringe\r','b'),
('b2','Tumori Maligni Dell''Apparato Digerente E Del Peritoneo\r','b'),
('b3','Tumori Maligni Dell''Apparato Respiratorio E Degli Organi Intratoracici\r','b'),
('b4','Tumori Maligni Delle Ossa, Del Tessuto Connettivo, Della Cute E Della Mammella\r','b'),
('b5','Tumori Maligni Degli Organi Genitourinari\r','b'),
('b6','Tumori Maligni Di Altre E Non Specificate Sedi\r','b'),
('b7','Tumori Maligni Del Tessuto Linfatico Ed Emopoietico\r','b'),
('b8','Tumori Benigni\r','b'),
('b9','Carcinomi In Situ\r','b'),
('b10','Tumori Di Comportamento Incerto\r','b'),
('b11','Tumori Di Natura Non Specificata\r','b'),
('c1','Disturbi Della Ghiandola Tiroidea\r','c'),
('c2','Disturbi Di Altre Ghiandole Endocrine\r','c'),
('c3','Deficienze Nutrizionali\r','c'),
('c4','Altri Disturbi Metabolici Ed Immunitari\r','c'),
('d1','Malattie Del Sangue E Degli Organi Ematopoietici\r','d'),
('e1','Stati Psicotici Organici\r','e'),
('e2','Disturbi Nevrotici E Della Personalita'' E Altri Disturbi Psichici Non Psicotici\r','e'),
('e3','Ritardo Mentale\r','e'),
('f1','Malattie Infiammatorie Del Sistema Nervoso Centrale\r','f'),
('f2','Disturbi Organici Del Sonno\r','f'),
('f3','Malattie Ereditarie E Degenerative Del Sistema Nervoso Centrale\r','f'),
('f4','Dolore\r','f'),
('f5','Altri Disturbi Del Sistema Nervoso Centrale\r','f'),
('f6','Disturbi Del Sistema Nervoso Periferico\r','f'),
('f7','Malattie Dell''Occhio E Degli Annessi\r','f'),
('f8','Malattie Dell''Orecchio E Dell''Apofisi Mastoide\r','f'),
('g1','Reumatismo Articolare Acuto\r','g'),
('g2','Cardiopatie Reumatiche Croniche\r','g'),
('g3','Pertensione Arteriosa\r','g'),
('g4','Malattie Ischemiche Del Cuore\r','g'),
('g5','Malattie Del Circolo Polmonare\r','g'),
('g6','Altre Malattie Del Cuore\r','g'),
('g7','Malattie Cerebrovascolari\r','g'),
('g8','Malattie Delle Arterie, Arteriole E Capillari\r','g'),
('g9','Malattie Delle Vene E Dei Vasi Linfatici Ed Altre Malattie Del Sistema Circolatorio\r','g'),
('i1','Infezioni Acute Delle Vie Respiratorie\r','i'),
('i2','Altre Malattie Delle Vie Respiratorie Superiori\r','i'),
('i3','Polmonite E Influenza\r','i'),
('i4','Malattie Polmonari Croniche Ostruttive E Manifestazioni Associate\r','i'),
('i5','Pneumoconiosi E Altre Malattie Del Polmone Da Agenti Esterni\r','i'),
('i6','Altre Malattie Del Sistema Respiratorio\r','i'),
('m1','Malattie Della Cavita'' Orale, Delle Ghiandole Salivari E Delle Mascelle\r','m'),
('m2','Malattie Dell''Esofago, Stomaco E Duodeno\r','m'),
('m3','Appendicite\r','m'),
('m4','Ernie Della Cavita''Addominale\r','m'),
('m5','Enteriti E Coliti Non Infettive\r','m'),
('m6','Altre Malattie Dell''Intestino E Del Peritoneo\r','m'),
('m7','Altre Malattie Dell''Apparato Digerente\r','m'),
('n1','Nefrite, Sindrome Nefrosica, E Nefrosi\r','n'),
('n2','Altre Patologie Del Sistema Urinario\r','n'),
('n3','Patologie Degli Organi Genitali Maschili\r','n'),
('n4','Disturbi Dela Mammella\r','n'),
('n5','Malattie Infiammatorie Degli Organi Pelvici Femminili\r','n'),
('n6','Altre Malattie Dell''Apparato Genitale Femminile\r','n'),
('o1','Gravidanza E Mola Vescicolare\r','o'),
('o2','Altre Gravidanze Con Esito Abortivo\r','o'),
('o3','Complicazioni Principalmente Correlate Alla Gravidanza\r','o'),
('o4','Parto Normale E Altre Indicazioni Per Ricovero In Gravidanza, Travaglio E Parto\r','o'),
('o5','Complicazioni Che Avvengono Principalmente Nel Corso Del Travaglio E Del Parto\r','o'),
('o6','Complicazioni Del Puerperio\r','o'),
('p1','Infezioni Della Cute E Del Tessuto Sottocutaneo\r','p'),
('p2','Altre Manifestazioni Infiammatorie Della Cute E Del Tessuto Sottocutaneo\r','p'),
('p3','Altro\r','p'),
('r1','Artropatie E Disturbi Correlati\r','r'),
('r2','Dorsopatie\r','r'),
('r3','Reumatismo, Escluse Le Forme Dorsali\r','r'),
('r4','Osteopatie, Condropatie E Deformita'' Acquisite Del Sistema Muscoloscheletrico\r','r'),
('s1','Malformazioni Congenite\r','s'),
('t1','Cause Materne Di Morbosita'' E Mortalita'' Perinatale\r','t'),
('t2','Altre Manifestazioni Originate Nel Periodo Neonatale\r','t'),
('v1','Sintomi\r','v'),
('v2','Reperti Anormali Non Specifici\r','v'),
('v3','Cause Mal Definite E Sconosciute Di Morbosita E Mortalita\r','v'),
('x1','Frattura\r','x'),
('x2','Lussazioni\r','x'),
('x3','Distorsioni E Distrazioni Delle Articolazioni E Dei Muscoli Adiacenti\r','x'),
('x4','Traumatismi Intracranici, Esclusi Quelli Associati A Frattura Del Cranio\r','x'),
('x5','Traumatismi Interni Del Torace, Dell''Addome E Della Pelvi\r','x'),
('x6','Ferite Aperte Di Testa, Collo E Tronco\r','x'),
('x7','Ferite Dell''Arto Superiore\r','x'),
('x8','Ferite Dell''Arto Inferiore\r','x'),
('x9','Traumatismi Dei Vasi Sanguigni\r','x'),
('x10','Postumi Di Traumatismi, Avvelenamenti, Effetti Tossici Ed Altre Cause Esterne\r','x'),
('x11','Traumatismi Superficiali\r','x'),
('x12','Contusioni Senza Soluzione Di Continuo\r','x'),
('x13','Schiacciamento\r','x'),
('x14','Effetti Da Corpo Estraneo Penetrato Attraverso Un Orifizio Naturale\r','x'),
('x15','Ustioni\r','x'),
('x16','Traumatismi Dei Nervi E Del Midollo Spinale\r','x'),
('x17','Alcune Complicazioni Traumatiche E Traumatismi Non Specificati\r','x'),
('x18','Avvelenamento Da Farmaci, Medicamenti E Prodotti Biologici\r','x'),
('x19','Effetti Tossici Di Sostanze Di Origine Principalmente Non Medicamentosa\r','x'),
('x20','Altri E Non Specificati Effetti Di Cause Esterne\r','x'),
('x21','Complicazioni Di Cure Mediche E Chirurgiche Non Classificate Altrove\r','x'),
('z1','Persone Con Rischi Potenziali Di Malattia In Relazione A Malattie Trasmissibili\r','z'),
('z2','Persone Con Necessita Di Isolamento, Altri Rischi Potenziali Di Malattia E Misure Profilattiche\r','z'),
('z3','Persone Con Rischi Potenziali Di Malattia In Relazione Alla Anamnesi Personale E Familiare\r','z'),
('z4','Persone Che Ricorrono Ai Servizi Sanitari In Circostanze Connesse Alla Riproduzione E Allo Sviluppo\r','z'),
('z5','Nati Vivi Sani Secondo Il Tipo Di Nascita\r','z'),
('z6','Persone In Patologie Particolari Che Influenzano Il Loro Stato Di Salute\r','z'),
('z7','Persone Che Ricorrono Ai Servizi Sanitari Per Specifici Trattamenti O Assistenza In Relazione A Cure Pregresse\r','z'),
('z8','Persone Che Ricorrono Ai Servizi Sanitari In Altre Circostanze\r','z'),
('z9','Persone Contattate Durante Visite E Esami Individuali E Collettivi Senza Indicazione Della Diagnosi\r','z'),
('z10','Genetica\r','z'),
('z11','Indice Di Massa Corporea\r','z'),
('z12','Stato Dei Recettori Degli Estrogeni\r','z'),
('y1','altro\r','y');