INSERT INTO `tbl_icd9_cat_diag_codici` (`codice_categoria`, `categoria_cod_descrizione`, `codice_blocco`) VALUES
('001','Colera\r','a1'),
('002','Febbre tifoide e paratifoide\r','a1'),
('003','Altre infezioni da Salmonella\r','a1'),
('004','Shigellosi\r','a1'),
('005','Altre intossicazioni alimentari (batteriche)\r','a1'),
('006','Amebiasi\r','a1'),
('007','Altre malattie intestinali da protozoi\r','a1'),
('008','Infezioni intestinali da altri organismi\r','a1'),
('009','Infezioni intestinali mal definite\r','a1'),
('010','Infezione tubercolare primaria\r','a2'),
('011','Tubercolosi polmonare\r','a2'),
('012','Altre forme di tubercolosi dell''apparato respiratorio\r','a2'),
('013','Tubercolosi delle meningi e del sistema nervoso\r','a2'),
('014','Tubercolosi dell''intestino, del peritoneo e delle ghiandole mesenteriche\r','a2'),
('015','Tubercolosi delle ossa e delle articolazioni\r','a2'),
('016','Tubercolosi dell''apparato genitourinario\r','a2'),
('017','Tubercolosi degli altri organi\r','a2'),
('018','Tubercolosi miliare\r','a2'),
('020','Peste\r','a3'),
('021','Tularemia\r','a3'),
('022','Carbonchio\r','a3'),
('023','Brucellosi\r','a3'),
('024','Morva\r','a3'),
('025','Melioidosi\r','a3'),
('026','Febbre da morso di ratto\r','a3'),
('027','Altre malattie batteriche trasmesse da animali\r','a3'),
('030','Lebbra\r','a4'),
('031','Malattie da altri micobatteri\r','a4'),
('032','Difterite\r','a4'),
('033','Pertosse\r','a4'),
('034','Angina streptococcica e scarlattina\r','a4'),
('035','Erisipela\r','a4'),
('036','Infezione meningococcica\r','a4'),
('037','Tetano\r','a4'),
('038','Setticemia\r','a4'),
('039','Infezioni actinomicotiche\r','a4'),
('040','Altre malattie batteriche\r','a4'),
('041','Infezioni batteriche in manifestazioni morbose classificate altrove e di sede non specificata\r','a4'),
('042','Infezione da virus della immunodeficienza umana (HIV)\r','a5'),
('045','Poliomielite acuta\r','a6'),
('046','Infezioni del sistema nervoso centrale da virus lenti\r','a6'),
('047','Meningite da Enterovirus\r','a6'),
('048','Altre malattie da Enterovirus del sistema nervoso centrale\r','a6'),
('049','Altre malattie virali del sistema nervoso centrale non trasmesse da artropodi\r','a6'),
('050','Vaiolo\r','a7'),
('051','Malattia vaccinica e similvaccinica\r','a7'),
('052','Varicella\r','a7'),
('053','Herpes zoster\r','a7'),
('054','Herpes simplex\r','a7'),
('055','Morbillo\r','a7'),
('056','Rosolia\r','a7'),
('057','Altri esantemi virali\r','a7'),
('060','Febbre gialla\r','a8'),
('061','Dengue\r','a8'),
('062','Encefalite virale da zanzare\r','a8'),
('063','Encefalite virale da zecche\r','a8'),
('064','Encefalite virale trasmessa da altri e non specificati artropodi\r','a8'),
('065','Febbre emorragica da artropodi\r','a8'),
('066','Altre malattie virali da artropodi\r','a8'),
('070','Epatite virale\r','a9'),
('071','Rabbia\r','a9'),
('072','Parotite epidemica\r','a9'),
('073','Psittacosi\r','a9'),
('074','Malattie specifiche da virus Coxsackie\r','a9'),
('075','Mononucleosi infettiva\r','a9'),
('076','Tracoma\r','a9'),
('077','Altre malattie della congiuntiva da virus e da Chlamydiae\r','a9'),
('078','Altre malattie da virus e da Chlamydiae\r','a9'),
('079','Infezioni da virus e Chlamydiae in manifestazioni morbose classificate altrove e di sede non specificata\r','a9'),
('080','Tifo [epidemico] da pidocchi\r','a10'),
('081','Altri tifi\r','a10'),
('082','Rickettsiosi da zecche\r','a10'),
('083','Altre rickettsiosi\r','a10'),
('084','Malaria\r','a10'),
('085','Leishmaniosi\r','a10'),
('086','Tripanosomiasi\r','a10'),
('087','Febbre ricorrente\r','a10'),
('088','Altre malattie da artropodi\r','a10'),
('090','Sifilide congenita\r','a11'),
('091','Sifilide recente con sintomi\r','a11'),
('092','Sifilide recente, latente\r','a11'),
('093','Sifilide cardiovascolare\r','a11'),
('094','Neurosifilide\r','a11'),
('095','Altre forme di sifilide tardiva con sintomi\r','a11'),
('096','Sifilide tardiva latente\r','a11'),
('097','Altre forme di sifilide e non specificata\r','a11'),
('098','Infezione gonococcica\r','a11'),
('099','Infezione gonococcica\r','a11'),
('100','Leptospirosi\r','a12'),
('101','Angina di Vincent\r','a12'),
('102','Framboesia\r','a12'),
('103','Pinta\r','a12'),
('104','Altre infezioni da spirochete\r','a12'),
('110','Dermatofitosi\r','a13'),
('111','Altre e non specificate dermatomicosi\r','a13'),
('112','Candidiasi\r','a13'),
('114','Coccidioidomicosi\r','a13'),
('115','Istoplasmosi\r','a13'),
('116','Infezione blastomicotica\r','a13'),
('117','Altre micosi\r','a13'),
('118','Micosi da patogeni facoltativi\r','a13'),
('120','Schistosomiasi (Bilarziosi)\r','a14'),
('121','Altre infestazioni da trematodi\r','a14'),
('122','Echinococcosi\r','a14'),
('123','Altre infezioni da cestodi\r','a14'),
('124','Trichinosi\r','a14'),
('125','Filariasi e dracontiasi\r','a14'),
('126','Anchilostomiasi e necatoriasi\r','a14'),
('127','Altre elmintiasi intestinali\r','a14'),
('128','Altre e non specificate elmintiasi\r','a14'),
('129','Parassitismo intestinale, non specificato\r','a14'),
('130','Toxoplasmosi\r','a15'),
('131','Tricomoniasi\r','a15'),
('132','Pediculosi e ftiriasi\r','a15'),
('133','Acariasi\r','a15'),
('134','Altre infestazioni\r','a15'),
('135','Sarcoidosi\r','a15'),
('136','Altre e non specificate malattie infettive e parassitarie\r','a15'),
('137','Postumi della tubercolosi\r','a16'),
('138','Postumi della poliomielite acuta\r','a16'),
('139','Postumi di altre malattie infettive e parassitarie\r','a16'),
('140','Tumori maligni delle labbra\r','b1'),
('141','Tumori maligni della lingua\r','b1'),
('142','Tumori maligni delle ghiandole salivari maggiori\r','b1'),
('143','Tumori maligni delle gengive\r','b1'),
('144','Tumori maligni del pavimento della bocca\r','b1'),
('145','Tumori maligni di altre e non specificate parti della bocca\r','b1'),
('146','Tumori maligni dell''orofaringe\r','b1'),
('147','Tumori maligni del rinofaringe\r','b1'),
('148','Tumori maligni dell''ipofaringe\r','b1'),
('149','Tumori maligni di altre e mal definite sedi delle labbra, della cavita'' orale e della faringe\r','b1'),
('150','Tumori maligni dell''esofago\r','b2'),
('151','Tumori maligni dello stomaco\r','b2'),
('152','Tumori maligni dell''intestino tenue, compreso il duodeno\r','b2'),
('153','Tumori maligni del colon\r','b2'),
('154','Tumori maligni del retto, della giunzione rettosigmoidea e dell''ano\r','b2'),
('155','Tumori maligni del fegato e dei dotti biliari intraepatici\r','b2'),
('156','Tumori maligni della colecisti e dei dotti biliari extraepatici\r','b2'),
('157','Tumori maligni del pancreas\r','b2'),
('158','Tumori maligni del retroperitoneo e del peritoneo\r','b2'),
('159','Tumori maligni di altre e mal definite sedi dell''apparato digerente e del peritoneo\r','b2'),
('160','Tumori maligni delle cavita'' nasali, dell''orecchio medio e dei seni paranasali\r','b3'),
('161','Tumori maligni della laringe\r','b3'),
('162','Tumori maligni della trachea, dei bronchi e dei polmoni\r','b3'),
('163','Tumori maligni della pleura\r','b3'),
('164','Tumori maligni del timo, del cuore e del mediastino\r','b3'),
('165','Tumori maligni di altre e mal definite sedi dell''apparato respiratorio e degli organi intratoracici\r','b3'),
('170','Tumori maligni delle ossa e delle cartilagini articolari\r','b4'),
('171','Tumori maligni del connettivo e di altri tessuti molli\r','b4'),
('172','Melanoma maligno della cute\r','b4'),
('173','Altri tumori maligni della cute\r','b4'),
('174','Tumori maligni della mammella della donna\r','b4'),
('175','Tumori maligni della mammella dell''uomo\r','b4'),
('176','Sarcoma di Kaposi\r','b4'),
('179','Tumori maligni dell''utero, parte non specificata\r','b5'),
('180','Tumori maligni del collo dell''utero (cervice uterina)\r','b5'),
('181','Tumori maligni della placenta\r','b5'),
('182','Tumori maligni del corpo dell''utero\r','b5'),
('183','Tumori maligni dell''ovaio e degli altri annessi uterini\r','b5'),
('184','Tumori maligni di altri e non specificati organi genitali femminili\r','b5'),
('185','Tumori maligni della prostata\r','b5'),
('186','Tumori maligni del testicolo\r','b5'),
('187','Tumori maligni del pene e degli altri organi genitali maschili\r','b5'),
('188','Tumori maligni della vescica\r','b5'),
('189','Tumori maligni del rene e di altri e non specificati organi urinari\r','b5'),
('190','Tumori maligni dell''occhio\r','b6'),
('191','Tumori maligni dell''encefalo\r','b6'),
('192','Tumori maligni di altre e non specificate parti del sistema nervoso\r','b6'),
('193','Tumori maligni della ghiandola tiroide\r','b6'),
('194','Tumori maligni delle altre ghiandole endocrine e strutture connesse\r','b6'),
('195','Tumori maligni di altre e mal definite sedi\r','b6'),
('196','Tumori maligni secondari e non specificati dei linfonodi\r','b6'),
('197','Tumori maligni secondari degli apparati respiratorio e digerente\r','b6'),
('198','Tumori maligni secondari di altre sedi specificate\r','b6'),
('199','Tumori maligni senza indicazione della sede\r','b6'),
('200','Linfosarcoma e reticolosarcoma\r','b7'),
('201','Malattia di Hodgkin\r','b7'),
('202','Altre neoplasie maligne del tessuto linfatico ed istiocitario\r','b7'),
('203','Mieloma multiplo e neoplasie immunoproliferative\r','b7'),
('204','Leucemia linfoide\r','b7'),
('205','Leucemia mieloide\r','b7'),
('206','Leucemia monocitica\r','b7'),
('207','Altre leucemie specifiche\r','b7'),
('208','Leucemia a tipo cellulare non specificato\r','b7'),
('210','Tumori benigni delle labbra, della cavita'' orale e della faringe\r','b8'),
('211','Tumori benigni di altre parti dell''apparato digerente\r','b8'),
('212','Tumori benigni dell''apparato respiratorio e degli organi intratoracici\r','b8'),
('213','Tumori benigni delle ossa e della cartilagine articolare\r','b8'),
('214','Lipoma\r','b8'),
('215','Altri tumori benigni del connettivo e di altri tessuti molli\r','b8'),
('216','Tumori benigni della cute\r','b8'),
('217','Tumori benigni della mammella\r','b8'),
('218','Leiomioma uterino\r','b8'),
('219','Altri tumori benigni dell''utero\r','b8'),
('220','Tumori benigni dell''ovaio\r','b8'),
('221','Tumori benigni degli altri organi genitali femminili\r','b8'),
('222','Tumori benigni degli organi genitali maschili\r','b8'),
('223','Tumori benigni del rene e degli altri organi urinari\r','b8'),
('224','Tumori benigni dell''occhio\r','b8'),
('225','Tumori benigni dell''encefalo e delle altre parti del sistema nervoso\r','b8'),
('226','Tumori benigni della ghiandola tiroide\r','b8'),
('227','Tumori benigni delle altre ghiandole endocrine e strutture connesse\r','b8'),
('228','Emangioma e linfangioma, ogni sede\r','b8'),
('229','Tumori benigni di altre e non specificate sedi\r','b8'),
('230','Carcinomi in situ degli organi digerenti\r','b9'),
('231','Carcinomi in situ dell''apparato respiratorio\r','b9'),
('232','Carcinomi in situ della cute\r','b9'),
('233','Carcinomi in situ della mammella e dell''apparato urogenitale\r','b9'),
('234','Carcinomi in situ di altre e non specificate sedi\r','b9'),
('235','Tumori di comportamento incerto degli apparati digerente e respiratorio\r','b10'),
('236','Tumori di comportamento incerto degli organi urogenitali\r','b10'),
('237','Tumori di comportamento incerto delle ghiandole endocrine e del sistema nervoso\r','b10'),
('238','Tumori di comportamento incerto di altri e non specificati tessuti e sedi\r','b10'),
('239','Tumori di natura non specificata\r','b11'),
('240','Gozzo semplice e non specificato\r','c1'),
('241','Gozzo nodulare non tossico\r','c1'),
('242','Tireotossicosi con o senza gozzo\r','c1'),
('243','Ipotiroidismo congenito\r','c1'),
('244','Ipotiroidismo acquisito\r','c1'),
('245','Tiroidite\r','c1'),
('246','Altri disturbi della tiroide\r','c1'),
('250','Diabete mellito\r','c2'),
('251','Altri disordini della secrezione endocrina del pancreas\r','c2'),
('252','Malattie delle ghiandole paratiroidi\r','c2'),
('253','Malattie ipotalamo-ipofisarie\r','c2'),
('254','Malattie del timo\r','c2'),
('255','Malattie delle ghiandole surrenali\r','c2'),
('256','Anomalie della funzione ovarica\r','c2'),
('257','Anomalie della funzione testicolare\r','c2'),
('258','Malattie plurighiandolari e disordini correlati\r','c2'),
('259','Altri disturbi endocrini\r','c2'),
('260','Kwashiorkor\r','c3'),
('261','Marasma da denutrizione\r','c3'),
('262','Altra grave malnutrizione proteico-calorica\r','c3'),
('263','Altra e non specificata malnutrizione proteico-calorica\r','c3'),
('264','Carenza di vitamina A\r','c3'),
('265','Stati carenziali di tiamina (vitamina B1) e di niacina\r','c3'),
('266','Carenza di componenti del complesso B\r','c3'),
('267','Carenza di acido ascorbico\r','c3'),
('268','Carenza di vitamina D\r','c3'),
('269','Altre carenze della nutrizione\r','c3'),
('270','Malattie del metabolismo e del trasporto degli aminoacidi\r','c4'),
('271','Disordini del metabolismo e del trasporto dei carboidrati\r','c4'),
('272','Disordini del metabolismo dei lipidi\r','c4'),
('273','Disordini del metabolismo delle proteine plasmatiche\r','c4'),
('274','Gotta\r','c4'),
('275','Disordini del metabolismo dei minerali\r','c4'),
('276','Disordini dei liquidi, degli elettroliti e dell''equilibrio acido-base\r','c4'),
('277','Altri e non specificati disordini del metabolismo\r','c4'),
('278','Sovrappeso, obesita'' ed altri stati di iperalimentazione\r','c4'),
('279','Malattie del sistema immunitario\r','c4'),
('280','Anemie da carenza di ferro\r','d1'),
('281','Altre anemie da carenza\r','d1'),
('282','Anemie emolitiche ereditarie\r','d1'),
('283','Anemia emolitica acquisita\r','d1'),
('284','Anemia aplastica e altre sindromi da insufficienza midollare\r','d1'),
('285','Altre e non specificate anemie\r','d1'),
('286','Difetti della coagulazione\r','d1'),
('287','Porpora ed altre manifestazioni emorragiche\r','d1'),
('288','Malattie dei globuli bianchi\r','d1'),
('289','Altre malattie del sangue e degli organi ematopoietici\r','d1'),
('290','Demenze\r','e1'),
('291','Disturbi mentali indotti da alcool\r','e1'),
('292','Disturbi mentali indotti da sostanze\r','e1'),
('293','Disturbi psichici transitori da condizioni patologiche classificate altrove\r','e1'),
('294','Disturbi mentali persistenti da condizioni patologiche classificate altrove\r','e1'),
('295','Psicosi schizofreniche\r','e1'),
('296','Disturbi episodici dell''umore\r','e1'),
('297','Disturbi deliranti\r','e1'),
('298','Altre psicosi non organiche\r','e1'),
('299','Disturbi pervasivi dello sviluppo\r','e1'),
('300','Disturbi d''ansia, dissociativi e somatoformi\r','e2'),
('301','Disturbi di personalita''\r','e2'),
('302','Disturbi sessuali e di identita'' di genere\r','e2'),
('303','Sindrome di dipendenza da alcool\r','e2'),
('304','Dipendenza da sostanze\r','e2'),
('305','Abuso di droghe senza dipendenza\r','e2'),
('306','Disfunzioni fisiologiche originate da fattori mentali\r','e2'),
('307','Sintomi o sindromi speciali non classificati altrove\r','e2'),
('308','Reazione acuta allo stress\r','e2'),
('309','Reazione di adattamento\r','e2'),
('310','Disturbi psichici specifici non psicotici dovuti a danno cerebrale\r','e2'),
('311','Disturbo depressivo, non classificato altrove\r','e2'),
('312','Disturbo della condotta, non classificato altrove\r','e2'),
('313','Disturbo delle emozioni specifico dell''infanzia e dell''adolescenza\r','e2'),
('314','Sindrome ipercinetica dell''infanzia\r','e2'),
('315','Ritardi specifici dello sviluppo\r','e2'),
('316','Fattori psichici associati a malattie classificate altrove\r','e2'),
('317','Ritardo mentale lieve\r','e3'),
('318','Altri ritardi mentali specificati\r','e3'),
('319','Ritardo mentale non specificato\r','e3'),
('320','Meningite batterica\r','f1'),
('321','Meningite da altri microrganismi\r','f1'),
('322','Meningite da causa non specificata\r','f1'),
('323','Encefalite, mielite, ed encefalomielite\r','f1'),
('324','Ascesso intracranico ed intrarachideo\r','f1'),
('325','Flebite e tromboflebite dei seni venosi intracranici\r','f1'),
('326','Postumi di ascesso intracranico o di infezione da piogeni\r','f1'),
('327','Disturbi organici del sonno\r','f2'),
('330','Degenerazioni cerebrali che si manifestano abitualmente nell''infanzia\r','f3'),
('331','Altre degenerazioni cerebrali\r','f3'),
('332','Morbo di Parkinson\r','f3'),
('333','Altre malattie extrapiramidali e altri disturbi del movimento\r','f3'),
('334','Malattie spinocerebellari\r','f3'),
('335','Malattie delle cellule delle corna anteriori\r','f3'),
('336','Altre malattie del midollo spinale\r','f3'),
('337','Disturbi del sistema nervoso autonomo\r','f3'),
('338','Dolore non classificato altrove\r','f4'),
('340','Sclerosi multipla\r','f5'),
('341','Altre malattie demielinizzanti del sistema nervoso centrale\r','f5'),
('342','Emiplegia e emiparesi\r','f5'),
('343','Paralisi cerebrale infantile\r','f5'),
('344','Altre sindromi paralitiche\r','f5'),
('345','Epilessie e crisi ricorrenti\r','f5'),
('346','Emicrania\r','f5'),
('347','Cataplessia e narcolessia\r','f5'),
('348','Altre condizioni patologiche dell''encefalo\r','f5'),
('349','Altri e non specificati disturbi del sistema nervoso\r','f5'),
('350','Disturbi del nervo trigemino\r','f6'),
('351','Disturbi del nervo facciale\r','f6'),
('352','Disturbi di altri nervi cranici\r','f6'),
('353','Disturbi delle radici e dei plessi nervosi\r','f6'),
('354','Mononeuriti dell''arto superiore e mononeuriti multiple\r','f6'),
('355','Mononeuriti dell''arto inferiore e di sede non specificata\r','f6'),
('356','Neuropatie periferiche ereditarie ed idiopatiche\r','f6'),
('357','Neuropatie infiammatorie e tossiche\r','f6'),
('358','Disturbi neuromuscolari\r','f6'),
('359','Distrofie muscolari e altre miopatie\r','f6'),
('360','Malattie del globo oculare\r','f7'),
('361','Distacco e rotture della retina\r','f7'),
('362','Altre malattie della retina\r','f7'),
('363','Infiammazioni corioretiniche, cicatrici e altre affezioni della coroide\r','f7'),
('364','Affezioni dell''iride e del corpo ciliare\r','f7'),
('365','Glaucoma\r','f7'),
('366','Cataratta\r','f7'),
('367','Vizi di rifrazione e disturbi dell''accomodazione\r','f7'),
('368','Disturbi visivi\r','f7'),
('369','Cecita'' e ipovisione\r','f7'),
('370','Cheratite\r','f7'),
('371','Opacita'' corneali e altre alterazioni della cornea\r','f7'),
('372','Malattie della congiuntiva\r','f7'),
('373','Infiammazione delle palpebre\r','f7'),
('374','Altre affezioni delle palpebre\r','f7'),
('375','Affezioni dell''apparato lacrimale\r','f7'),
('376','Affezioni dell''orbita\r','f7'),
('377','Malattie del nervo e delle vie ottiche\r','f7'),
('378','Strabismo ed altri disturbi dei movimenti binoculari\r','f7'),
('379','Altre malattie dell''occhio\r','f7'),
('380','Disturbi dell''orecchio esterno\r','f8'),
('381','Otite media non suppurativa e disturbi della tromba di Eustachio\r','f8'),
('382','Otite media suppurativa e non specificata\r','f8'),
('383','Mastoidite e manifestazioni morbose correlate\r','f8'),
('384','Altri disturbi della membrana timpanica\r','f8'),
('385','Altri disturbi dell''orecchio medio e della mastoide\r','f8'),
('386','Sindromi vertiginose ed altri disturbi del sistema vestibolare\r','f8'),
('387','Otosclerosi\r','f8'),
('388','Altri disturbi dell''orecchio\r','f8'),
('389','Perdita dell''udito\r','f8'),
('390','Febbre reumatica senza menzione di interessamento cardiaco\r','g1'),
('391','Febbre reumatica con complicazioni cardiache\r','g1'),
('392','Corea reumatica\r','g1'),
('393','Pericardite reumatica cronica\r','g2'),
('394','Malattie della valvola mitrale\r','g2'),
('395','Malattie della valvola aortica\r','g2'),
('396','Malattie delle valvole mitrale e aortica\r','g2'),
('397','Malattie di altre strutture endocardiche\r','g2'),
('398','Altre cardiopatie reumatiche\r','g2'),
('401','Ipertensione essenziale\r','g3'),
('402','Cardiopatia ipertensiva\r','g3'),
('403','Nefropatia ipertensiva cronica\r','g3'),
('404','Cardionefropatia ipertensiva\r','g3'),
('405','Ipertensione secondaria\r','g3'),
('410','Infarto miocardico acuto\r','g4'),
('411','Altre forme acute e subacute di cardiopatia ischemica\r','g4'),
('412','Infarto miocardico pregresso\r','g4'),
('413','Angina pectoris\r','g4'),
('414','Altre forme di cardiopatia ischemica cronica\r','g4'),
('415','Malattia cardiopolmonare acuta\r','g5'),
('416','Malattia cardiopolmonare cronica\r','g5'),
('417','Altre malattie del circolo polmonare\r','g5'),
('420','Pericardite acuta\r','g6'),
('421','Endocardite acuta e subacuta\r','g6'),
('422','Miocardite acuta\r','g6'),
('423','Altre malattie del pericardio\r','g6'),
('424','Altre malattie dell''endocardio\r','g6'),
('425','Cardiomiopatie\r','g6'),
('426','Disturbi della conduzione\r','g6'),
('427','Aritmie cardiache\r','g6'),
('428','Insufficienza cardiaca (scompenso cardiaco)\r','g6'),
('429','Forme e complicazioni mal definite di cardiopatie\r','g6'),
('430','Emorragia subaracnoidea\r','g7'),
('431','Emorragia cerebrale\r','g7'),
('432','Altre e non specificate emorragie intracraniche\r','g7'),
('433','Occlusione e stenosi delle arterie precerebrali\r','g7'),
('434','Occlusione delle arterie cerebrali\r','g7'),
('435','Ischemia cerebrale transitoria\r','g7'),
('436','Vasculopatie cerebrali acute, mal definite\r','g7'),
('437','Altre e mal definite vasculopatie cerebrali\r','g7'),
('438','Postumi delle malattie cerebrovascolari\r','g7'),
('440','Aterosclerosi\r','g8'),
('441','Aneurisma dell''aorta e dissezione\r','g8'),
('442','Altri aneurismi\r','g8'),
('443','Altre malattie vascolari periferiche\r','g8'),
('444','Embolia e trombosi arteriose\r','g8'),
('445','Ateroembolismo\r','g8'),
('446','Poliarterite nodosa e arteriti similari\r','g8'),
('447','Altri disturbi delle arterie e delle arteriole\r','g8'),
('448','Malattie dei capillari\r','g8'),
('451','Flebite e tromboflebite\r','g9'),
('452','Trombosi della vena porta\r','g9'),
('453','Embolia e trombosi di altre vene\r','g9'),
('454','Varici degli arti inferiori\r','g9'),
('455','Emorroidi\r','g9'),
('456','Varici di altre sedi\r','g9'),
('457','Disturbi non infettivi dei vasi linfatici\r','g9'),
('458','Ipotensione\r','g9'),
('459','Altri disturbi del sistema circolatorio\r','g9'),
('460','Rinofaringite acuta (raffreddore comune)\r','i1'),
('461','Sinusite acuta\r','i1'),
('462','Faringite acuta\r','i1'),
('463','Tonsillite acuta\r','i1'),
('464','Laringite e tracheite acuta\r','i1'),
('465','Infezioni acute delle vie respiratorie superiori a localizzazioni multiple o non specificate\r','i1'),
('466','Bronchite e bronchiolite acuta\r','i1'),
('470','Deviazione del setto nasale\r','i2'),
('471','Polipo nasale\r','i2'),
('472','Faringite e rinofaringite cronica\r','i2'),
('473','Sinusite cronica\r','i2'),
('474','Malattie croniche delle tonsille e delle adenoidi\r','i2'),
('475','Ascesso peritonsillare\r','i2'),
('476','Laringite e laringotracheite cronica\r','i2'),
('477','Rinite allergica\r','i2'),
('478','Altre malattie delle vie respiratorie superiori\r','i2'),
('480','Polmonite virale\r','i3'),
('481','Polmonite pneumococcica (polmonite da Streptococco pneumoniae)\r','i3'),
('482','Altre polmoniti batteriche\r','i3'),
('483','Polmonite da altri organismi specificati\r','i3'),
('484','Polmonite in malattie infettive classificate altrove\r','i3'),
('485','Broncopolmonite, agente non specificato\r','i3'),
('486','Polmonite, agente non specificato\r','i3'),
('487','Influenza\r','i3'),
('490','Bronchite, non specificata se acuta o cronica\r','i4'),
('491','Bronchite cronica\r','i4'),
('492','Enfisema\r','i4'),
('493','Asma\r','i4'),
('494','Bronchiectasie\r','i4'),
('495','Alveolite allergica estrinseca\r','i4'),
('496','Ostruzioni croniche delle vie respiratorie, non classificate altrove\r','i4'),
('500','Pneumoconiosi dei lavoratori del carbone\r','i5'),
('501','Asbestosi\r','i5'),
('502','Altre pneumoconiosi da silice e silicati\r','i5'),
('503','Pneumoconiosi da altre polveri inorganiche\r','i5'),
('504','Pneumoconiosi da inalazione di altre polveri\r','i5'),
('505','Pneumoconiosi, non specificata\r','i5'),
('506','Manifestazioni morbose respiratorie da inalazione di fumi e vapori chimici\r','i5'),
('507','Polmonite da solidi e liquidi\r','i5'),
('508','Manifestazioni morbose respiratorie da altri e non specificati agenti esterni\r','i5'),
('510','Empiema\r','i6'),
('511','Pleurite\r','i6'),
('512','Pneumotorace\r','i6'),
('513','Ascesso del polmone e del mediastino\r','i6'),
('514','Congestione ed ipostasi polmonare\r','i6'),
('515','Fibrosi polmonare postinfiammatoria\r','i6'),
('516','Altre pneumopatie alveolari e parietoalveolari\r','i6'),
('517','Complicazioni polmonari in manifestazioni morbose classificate altrove\r','i6'),
('518','Altre malattie del polmone\r','i6'),
('519','Altre malattie dell''apparato respiratorio\r','i6'),
('520','Disordini dello sviluppo e della eruzione del dente\r','m1'),
('521','Malattie dei tessuti duri dei denti\r','m1'),
('522','Malattie della polpa e dei tessuti periapicali\r','m1'),
('523','Malattie gengivali e periodontali\r','m1'),
('524','Anomalie odontofacciali, inclusa la malocclusione\r','m1'),
('525','Altre malattie e condizioni dei denti e delle strutture di supporto\r','m1'),
('526','Malattie delle mascelle\r','m1'),
('527','Malattie delle ghiandole salivari\r','m1'),
('528','Malattie dei tessuti molli orali, escluse specifiche lesioni della gengiva e della lingua\r','m1'),
('529','Malattie ed altre manifestazioni morbose della lingua\r','m1'),
('530','Malattie dell''esofago\r','m2'),
('531','Ulcera gastrica\r','m2'),
('532','Ulcera duodenale\r','m2'),
('533','Ulcera peptica, sito non specificato\r','m2'),
('534','Ulcera gastrodigiunale\r','m2'),
('535','Gastrite e duodenite\r','m2'),
('536','Disturbi della funzione gastrica\r','m2'),
('537','Altri disturbi dello stomaco e del duodeno\r','m2'),
('538','Mucosite gastrointestinale (ulcerativa)\r','m2'),
('540','Appendicite acuta\r','m3'),
('541','Appendicite, non precisata\r','m3'),
('542','Altre forme di appendicite\r','m3'),
('543','Altre malattie dell''appendice\r','m3'),
('550','Ernia inguinale\r','m4'),
('551','Altra ernia della cavita'' addominale, con gangrena\r','m4'),
('552','Altra ernia della cavita'' addominale con ostruzione, ma senza menzione di gangrena\r','m4'),
('553','Altra ernia della cavita'' addominale senza menzione di ostruzione o gangrena\r','m4'),
('555','Enterite regionale\r','m5'),
('556','Colite ulcerosa\r','m5'),
('557','Insufficienza vascolare dell''intestino\r','m5'),
('558','Altra gastroenterite e colite non infettiva\r','m5'),
('560','Occlusione intestinale senza menzione di ernia\r','m6'),
('562','Diverticoli dell''intestino\r','m6'),
('564','Disturbi digestivi funzionali, non classificati altrove\r','m6'),
('565','Ragade e fistola anali\r','m6'),
('566','Ascesso anale e rettale\r','m6'),
('567','Peritonite ed infezione retroperitoneale\r','m6'),
('568','Altri disturbi del peritoneo\r','m6'),
('569','Altri disturbi dell''intestino\r','m6'),
('570','Necrosi acuta e subacuta del fegato\r','m7'),
('571','Malattia epatica cronica e cirrosi\r','m7'),
('572','Ascesso del fegato e postumi di malattie croniche del fegato\r','m7'),
('573','Altri disturbi del fegato\r','m7'),
('574','Colelitiasi\r','m7'),
('575','Altri disturbi della colecisti\r','m7'),
('576','Altri disturbi delle vie biliari\r','m7'),
('577','Malattie del pancreas\r','m7'),
('578','Emorragia gastrointestinale\r','m7'),
('579','Malassorbimento intestinale\r','m7'),
('580','Glomerulonefrite acuta\r','n1'),
('581','Sindrome nefrosica\r','n1'),
('582','Glomerulonefrite cronica\r','n1'),
('583','Nefrite e nefropatia, non specificate come acute o croniche\r','n1'),
('584','Insufficienza renale acuta\r','n1'),
('585','Malattia renale cronica (CKD)\r','n1'),
('586','Insufficienza renale, non specificata\r','n1'),
('587','Sclerosi renale, non specificata\r','n1'),
('588','Patologie causate da ridotta funzione renale\r','n1'),
('589','Rene piccolo da causa ignota\r','n1'),
('590','Infezioni del rene\r','n2'),
('591','Idronefrosi\r','n2'),
('592','Calcolosi renale ed ureterale\r','n2'),
('593','Altre patologie del rene e dell''uretere\r','n2'),
('594','Calcolo del tratto urinario inferiore\r','n2'),
('595','Cistite\r','n2'),
('596','Altre patologie della vescica\r','n2'),
('597','Uretrite, non trasmessa sessualmente, e sindrome uretrale\r','n2'),
('598','Stenosi uretrale\r','n2'),
('599','Altre patologie dell''uretra e del sistema urinario\r','n2'),
('600','Iperplasia della prostata\r','n3'),
('601','Patologie infiammatorie della prostata\r','n3'),
('602','Altre patologie della prostata\r','n3'),
('603','Idrocele\r','n3'),
('604','Orchite ed epididimite\r','n3'),
('605','Prepuzio esuberante e fimosi\r','n3'),
('606','Infertilita'' maschile\r','n3'),
('607','Patologie del pene\r','n3'),
('608','Altre patologie degli organi genitali maschili\r','n3'),
('610','Displasia benigna della mammella\r','n4'),
('611','Altri disturbi della mammella\r','n4'),
('614','Malattie infiammatorie dell''ovaio, delle tube, del tessuto cellulare pelvico e del peritoneo\r','n5'),
('615','Malattie infiammatorie dell''utero, esclusa la cervice\r','n5'),
('616','Malattia infiammatoria della cervice, della vagina e della vulva\r','n5'),
('617','Endometriosi\r','n6'),
('618','Prolasso genitale\r','n6'),
('619','Fistola che interessa il tratto genitale femminile\r','n6'),
('620','Patologie non infiammatorie dell''ovaio, della salpinge e del legamento largo\r','n6'),
('621','Patologie dell''utero non classificate altrove\r','n6'),
('622','Patologie non infiammatorie della cervice\r','n6'),
('623','Patologie non infiammatorie della vagina\r','n6'),
('624','Patologie non infiammatorie della vulva e del perineo\r','n6'),
('625','Dolore e altri sintomi associati agli organi genitali femminili\r','n6'),
('626','Disordini mestruali ed altri sanguinamenti anomali del tratto genitale femminile\r','n6'),
('627','Sanguinamento postcoitale\r','n6'),
('628','Infertilita'' femminile\r','n6'),
('629','Altre patologie degli organi genitali femminili\r','n6'),
('630','Mola idatiforme\r','o1'),
('631','Altri prodotti del concepimento anomali\r','o1'),
('632','Aborto ritenuto\r','o1'),
('633','Gravidanza ectopica\r','o1'),
('634','Aborto spontaneo\r','o2'),
('635','Aborto indotto legalmente\r','o2'),
('636','Aborto illegale\r','o2'),
('637','Aborto non specificato\r','o2'),
('638','Tentativo fallito di aborto\r','o2'),
('639','Complicazioni successive ad aborto e gravidanze ectopiche e molari\r','o2'),
('640','Perdita ematica nella fase iniziale della gravidanza\r','o3'),
('641','Perdita ematica antepartum, abruptio placentae e placenta previa\r','o3'),
('642','Ipertensione complicante la gravidanza, il parto e il puerperio\r','o3'),
('643','Vomito incontrollabile in gravidanza\r','o3'),
('644','Minaccia o travaglio di parto precoce\r','o3'),
('645','Gravidanza ritardata\r','o3'),
('646','Altre complicazioni della gravidanza non classificate altrove\r','o3'),
('647','Manifestazioni infettive e parassitarie nella madre, classificabili altrove, ma complicanti la gravidanza, il parto o il puerperio\r','o3'),
('648','Altre manifestazioni morbose in atto della madre classificate altrove, ma complicanti la gravidanza, il parto o il puerperio\r','o3'),
('649','Altre manifestazioni morbose in atto della madre complicanti la gravidanza, il parto o il puerperio\r','o3'),
('650','Parto normale\r','o4'),
('651','Gravidanza multipla\r','o4'),
('652','Posizione e presentazione anomale del feto\r','o4'),
('653','Sproporzione\r','o4'),
('654','Anomalie degli organi e dei tessuti molli della pelvi\r','o4'),
('655','Anomalia fetale, conosciuta o sospetta che influenza il trattamento della madre\r','o4'),
('656','Altri problemi fetali e placentari che interferiscono con il trattamento della madre\r','o4'),
('657','Polidramnios\r','o4'),
('658','Altri problemi collegati alla cavita'' amniotica e alle membrane\r','o4'),
('659','Altre indicazioni per l''assistenza o l''intervento relative al travaglio e al parto, non classificate altrove\r','o4'),
('660','Travaglio ostacolato\r','o5'),
('661','Anomalie delle contrazioni uterine in travaglio\r','o5'),
('662','Travaglio prolungato\r','o5'),
('663','Complicazioni del cordone ombelicale\r','o5'),
('664','Trauma del perineo e della vulva nel corso del parto\r','o5'),
('665','Altri traumi ostetrici\r','o5'),
('666','Emorragia postpartum\r','o5'),
('667','Ritenzione della placenta o delle membrane, senza emorragia\r','o5'),
('668','Complicazioni da somministrazione di anestetici o altri sedativi nel corso del travaglio e del parto\r','o5'),
('669','Altre complicazioni del travaglio e del parto, non altrimenti classificate\r','o5'),
('670','Infezioni puerperali maggiori\r','o6'),
('671','Complicazioni venose della gravidanza e del puerperio\r','o6'),
('672','Piressia di origine ignota durante il puerperio\r','o6'),
('673','Embolia polmonare ostetrica\r','o6'),
('674','Altre e non specificate complicazioni del puerperio, non classificate altrove\r','o6'),
('675','Ascesso della mammella\r','o6'),
('676','Altri problemi del seno associati con la gravidanza, il puerperio e l''allattazione\r','o6'),
('677','Effetto tardivo della complicazione della gravidanza, del parto, del puerperio\r','o6'),
('680','Foruncolo e favo\r','p1'),
('681','Flemmone e ascesso delle dita delle mani e delle dita dei piedi\r','p1'),
('682','Altri flemmoni e ascessi\r','p1'),
('683','Linfadenite acuta\r','p1'),
('684','Impetigine\r','p1'),
('685','Cisti pilonidale\r','p1'),
('686','Altre infezioni localizzate della cute e del tessuto sottocutaneo\r','p1'),
('690','Dermatosi eritemato-desquamative\r','p2'),
('691','Dermatite atopica e affezioni correlate\r','p2'),
('692','Dermatite da contatto ed altri eczemi\r','p2'),
('693','Dermatiti da sostanze assunte per via sistemica\r','p2'),
('694','Dermatosi bollose\r','p2'),
('695','Affezioni eritematose\r','p2'),
('696','Psoriasi e affezioni similari\r','p2'),
('697','Lichen\r','p2'),
('698','Prurito e affezioni correlate\r','p2'),
('700','Calli e callosita''\r','p3'),
('701','Altre affezioni atrofiche e ipertrofiche della cute\r','p3'),
('702','Altre dermatosi\r','p3'),
('703','Malattie delle unghie\r','p3'),
('704','Malattie dei peli e dei follicoli piliferi\r','p3'),
('705','Malattie delle ghiandole sudoripare\r','p3'),
('706','Malattie delle ghiandole sebacee\r','p3'),
('707','Ulcerazione cronica della cute\r','p3'),
('708','Orticaria\r','p3'),
('709','Altre alterazioni della cute e del tessuto sottocutaneo\r','p3'),
('710','Malattie diffuse del tessuto connettivo\r','r1'),
('711','Artropatie da agenti infettivi\r','r1'),
('712','Artropatie da microcristalli\r','r1'),
('713','Artropatia associata ad altri disturbi classificati altrove\r','r1'),
('714','Artrite reumatoide ed altre poliartropatie infiammatorie\r','r1'),
('715','Artrosi\r','r1'),
('716','Altre artropatie non specificate\r','r1'),
('717','Lesioni interne del ginocchio\r','r1'),
('718','Altre lesioni articolari\r','r1'),
('719','Altre e non specificate patologie articolari\r','r1'),
('720','Spondilite anchilosante ed altre spondilopatie infiammatorie\r','r2'),
('721','Spondilosi e disturbi associati\r','r2'),
('722','Patologie dei dischi intervertebrali\r','r2'),
('723','Altre patologie della regione cervicale\r','r2'),
('724','Altri e non specificati disturbi del dorso\r','r2'),
('725','Polimialgia reumatica\r','r3'),
('726','Entesopatie periferiche e sindromi analoghe\r','r3'),
('727','Altri disturbi delle membrane sinoviali, dei tendini e delle borse\r','r3'),
('728','Patologie dei muscoli, dei legamenti e delle fasce\r','r3'),
('729','Altri disturbi dei tessuti molli\r','r3'),
('730','Osteomielite, periostite e altre infezioni ossee\r','r4'),
('731','Osteite deformante e osteopatie associate ad altri disturbi classificati altrove\r','r4'),
('732','Osteocondropatie\r','r4'),
('733','Altri disturbi delle ossa e delle cartilagini\r','r4'),
('734','Piede piatto\r','r4'),
('735','Deformazioni acquisite delle dita del piede\r','r4'),
('736','Altre deformazioni acquisite degli arti\r','r4'),
('737','Deviazioni della colonna vertebrale\r','r4'),
('738','Altre deformazioni acquisite dell''apparato muscoloscheletrico\r','r4'),
('739','Lesioni non allopatiche, non classificate altrove\r','r4'),
('740','Anencefalia e anomalie simili\r','s1'),
('741','Spina bifida\r','s1'),
('742','Altre anomalie congenite del sistema nervoso\r','s1'),
('743','nomalie congenite dell''occhio\r','s1'),
('744','Anomalie congenite dell''orecchio, della faccia e del collo\r','s1'),
('745','Anomalie del bulbo cardiaco e anomalie della chiusura del setto cardiaco\r','s1'),
('746','Altre anomalie congenite del cuore\r','s1'),
('747','Altre anomalie congenite del sistema circolatorio\r','s1'),
('748','Anomalie congenite dell''apparato respiratorio\r','s1'),
('749','Palatoschisi e labioschisi\r','s1'),
('750','Altre anomalie congenite del tratto alimentare superiore\r','s1'),
('751','Altre anomalie congenite del sistema digestivo\r','s1'),
('752','Anomalie congenite degli organi genitali\r','s1'),
('753','Anomalie congenite del sistema urinario\r','s1'),
('754','Alcune malformazioni congenite del sistema muscoloscheletrico\r','s1'),
('755','Altre anomalie congenite degli arti\r','s1'),
('756','Altre anomalie muscoloscheletriche congenite\r','s1'),
('757','Anomalie congenite del tegumento\r','s1'),
('758','Anomalie cromosomiche\r','s1'),
('759','Altre anomalie congenite non specificate\r','s1'),
('760','Manifestazioni morbose del feto o del neonato derivanti da patologia materna anche non correlata alla gravidanza attuale\r','t1'),
('761','Feto o neonato affetto da complicazioni materne della gravidanza\r','t1'),
('762','Feto o neonato affetto da complicazioni della placenta, del cordone ombelicale e delle membrane\r','t1'),
('763','Feto o neonato affetto da altre complicazioni del travaglio e del parto\r','t1'),
('764','Ritardo di crescita fetale e malnutrizione fetale\r','t2'),
('765','Problemi relativi a bassa eta'' gestazionale e basso peso alla nascita\r','t2'),
('766','Problemi relativi a gravidanza protratta e macrosomia\r','t2'),
('767','Traumi ostetrici\r','t2'),
('768','Ipossia intrauterina e asfissia alla nascita\r','t2'),
('769','Sindrome da distress respiratorio neonatale\r','t2'),
('770','Altre malattie respiratorie del feto e del neonato\r','t2'),
('771','Infezioni specifiche del periodo perinatale\r','t2'),
('772','Emorragia fetale e neonatale\r','t2'),
('773','Malattia emolitica del feto o del neonato dovuta a isoimmunizzazione materno fetale\r','t2'),
('774','Altro ittero perinatale\r','t2'),
('775','Disturbi endocrini e metabolici specifici del feto e del neonato\r','t2'),
('776','Disturbi ematologici del feto e del neonato\r','t2'),
('777','Malattie dell''apparato digerente del feto o del neonato\r','t2'),
('778','Manifestazioni morbose interessanti la cute e la regolazione termica del feto e del neonato\r','t2'),
('779','Altre e mal definite manifestazioni morbose ad insorgenza perinatale\r','t2'),
('780','Sintomi generali\r','v1'),
('781','Sintomi interessanti i sistemi nervoso e osteomuscolare\r','v1'),
('782','Sintomi interessanti la cute e gli altri tessuti tegumentari\r','v1'),
('783','Sintomi relativi alla nutrizione, al metabolismo e allo sviluppo\r','v1'),
('784','Sintomi relativi alla testa e al collo\r','v1'),
('785','Sintomi relativi al sistema cardiovascolare\r','v1'),
('786','Sintomi relativi all''apparato respiratorio ed altri sintomi toracici\r','v1'),
('787','Sintomi relativi all''apparato digerente\r','v1'),
('788','Sintomi relativi all''apparato urinario\r','v1'),
('789','Altri sintomi relativi all''addome e al bacino\r','v1'),
('790','Reperti non specifici dell''esame di sangue\r','v2'),
('791','Reperti non specifici dell''esame urine\r','v2'),
('792','Reperti anormali non specifici in altre sostanze corporee\r','v2'),
('793','Reperti anormali non specifici in esami radiologici e in altri esami delle strutture corporee\r','v2'),
('794','Risultati anormali non specifici di prove funzionali\r','v2'),
('795','Altri e non specifici reperti citologici, istologici, immunologici anomali anomalie del test del DNA\r','v2'),
('796','Altri reperti anormali non specifici\r','v2'),
('797','Senilita'' senza menzione di psicosi\r','v3'),
('798','Morte improvvisa da causa sconosciuta\r','v3'),
('799','Altre cause mal definite e sconosciute di morbosita'' e mortalita''\r','v3'),
('800','Frattura della volta cranica\r','x1'),
('801','Frattura della base cranica\r','x1'),
('802','Frattura delle ossa della faccia\r','x1'),
('803','Altre e non specificate fratture del cranio\r','x1'),
('804','Fratture multiple relative al cranio o alla faccia unitamente con altre ossa\r','x1'),
('805','Frattura della colonna vertebrale senza menzione di lesione del midollo spinale\r','x1'),
('806','Frattura della colonna vertebrale con lesione del midollo spinale\r','x1'),
('807','Frattura delle costola(e), dello sterno, della laringe e della trachea\r','x1'),
('808','Frattura del bacino\r','x1'),
('809','Fratture mal definite del tronco\r','x1'),
('810','Frattura della clavicola\r','x1'),
('811','Frattura della scapola\r','x1'),
('812','Frattura dell''omero\r','x1'),
('813','Frattura del radio e dell''ulna\r','x1'),
('814','Frattura delle ossa del carpo\r','x1'),
('815','Frattura delle ossa del metacarpo\r','x1'),
('816','Frattura di una o piu'' falangi della mano\r','x1'),
('817','Fratture multiple delle ossa della mano\r','x1'),
('818','Fratture mal definite dell''arto superiore\r','x1'),
('819','Fratture multiple di ambedue gli arti superiori e dell''arto superiore con le costole e lo sterno\r','x1'),
('820','Frattura del collo del femore\r','x1'),
('821','Frattura di altre e non specificate parti del femore\r','x1'),
('822','Frattura della rotula\r','x1'),
('823','Frattura della tibia e del perone\r','x1'),
('824','Frattura della caviglia\r','x1'),
('825','Frattura di una o piu'' ossa del tarso e metatarso\r','x1'),
('826','Frattura di una o piu'' falangi del piede\r','x1'),
('827','Altre, multiple e mal definite fratture dell''arto inferiore\r','x1'),
('828','Fratture multiple interessanti ambedue gli arti inferiori, l''arto inferiore con quello superiore e l''arto inferiore con le costole e lo sterno\r','x1'),
('829','Fratture di ossa non specificate\r','x1'),
('830','Lussazione della mandibola\r','x2'),
('831','Lussazione della spalla\r','x2'),
('832','Lussazione del gomito\r','x2'),
('833','Lussazione del polso\r','x2'),
('834','Lussazione delle dita della mano\r','x2'),
('835','Lussazione dell''anca\r','x2'),
('836','Lussazione del ginocchio\r','x2'),
('837','Lussazione della caviglia\r','x2'),
('838','Lussazione del piede\r','x2'),
('839','Altre, multiple e mal definite lussazioni\r','x2'),
('840','Distorsione e distrazione della spalla e del braccio\r','x3'),
('841','Distorsione e distrazione del gomito e dell''avambraccio\r','x3'),
('842','Distorsione e distrazione del polso e della mano\r','x3'),
('843','Distorsione e distrazione dell''anca e della coscia\r','x3'),
('844','Distorsione e distrazione del ginocchio e della gamba\r','x3'),
('845','Distorsione e distrazione della caviglia e del piede\r','x3'),
('846','Distorsione e distrazione della regione sacroiliaca\r','x3'),
('847','Distorsione e distrazione di altre e non specificate parti del dorso\r','x3'),
('848','Altre e mal definite distorsioni e distrazioni\r','x3'),
('850','Concussione\r','x4'),
('851','Lacerazione e contusione cerebrali\r','x4'),
('852','Emorragia subaracnoidea, subdurale ed extradurale consecutive a traumatismo\r','x4'),
('853','Altre e non specificate emorragie intracraniche consecutive a traumatismo\r','x4'),
('854','Traumatismi intracranici di altra e non specificata natura\r','x4'),
('860','Pneumotorace ed emotorace traumatici\r','x5'),
('861','Traumatismo del cuore e del polmone\r','x5'),
('862','Traumatismo di altri e non specificati organi intratoracici\r','x5'),
('863','Traumatismo dell''apparato gastrointestinale\r','x5'),
('864','Traumatismo del fegato\r','x5'),
('865','Traumatismo della milza\r','x5'),
('866','Traumatismo del rene\r','x5'),
('867','Traumatismo degli organi pelvici\r','x5'),
('868','Traumatismo di altri organi intraddominali\r','x5'),
('869','Traumatismo interno di organi non specificati o mal definiti\r','x5'),
('870','Ferita degli annessi oculari\r','x6'),
('871','Ferita del globo oculare\r','x6'),
('872','Ferita dell''orecchio\r','x6'),
('873','Altre ferite della testa\r','x6'),
('874','Ferita del collo\r','x6'),
('875','Ferita del torace (parete)\r','x6'),
('876','Ferita del dorso\r','x6'),
('877','Ferita della natica\r','x6'),
('878','Ferita degli organi genitali (esterni), compresa l''amputazione traumatica\r','x6'),
('879','Ferite di altre e non specificate sedi, esclusi gli arti\r','x6'),
('880','Ferita della spalla e del braccio\r','x7'),
('881','Ferita del gomito, dell''avambraccio e del polso\r','x7'),
('882','Ferita della mano, escluse le dita da sole\r','x7'),
('883','Ferita delle dita della mano\r','x7'),
('884','Ferite multiple e non specificate dell''arto superiore\r','x7'),
('885','Amputazione traumatica del pollice (completa) (parziale)\r','x7'),
('886','Amputazione traumatica delle altre dita della mano (completa) (parziale)\r','x7'),
('887','Amputazione traumatica del braccio e della mano (completa) (parziale)\r','x7'),
('890','Ferita dell''anca e della coscia\r','x8'),
('891','Ferita del ginocchio, della gamba [esclusa la coscia] e della caviglia\r','x8'),
('892','Ferita del piede, escluse le dita da sole\r','x8'),
('893','Ferita delle dita del piede\r','x8'),
('894','Ferite multiple e non specificate dell''arto inferiore\r','x8'),
('895','Amputazione traumatica delle dita del piede (completa) (parziale)\r','x8'),
('896','Amputazione traumatica del piede (completa) (parziale)\r','x8'),
('897','Amputazione traumatica della gamba (completa) (parziale)\r','x8'),
('900','Traumatismo dei vasi sanguigni della testa e del collo\r','x9'),
('901','Traumatismo dei vasi sanguigni del torace\r','x9'),
('902','Traumatismo dei vasi sanguigni dell''addome e del bacino\r','x9'),
('903','Traumatismo dei vasi sanguigni dell''arto superiore\r','x9'),
('904','Trumatismo dei vasi sanguigni dell''arto inferiore e di sede non specificata\r','x9'),
('905','Postumi di traumatismi del sistema osteomuscolare e del tessuto connettivo\r','x10'),
('906','Postumi di traumatismi della pelle e del tessuto sottocutaneo\r','x10'),
('907','Postumi di traumatismi del sistema nervoso\r','x10'),
('908','Postumi di altri e non specificati traumatismi\r','x10'),
('909','Postumi di altre e non specificate cause esterne\r','x10'),
('910','Traumatismo superficiale della faccia, del collo e del cuoio capelluto, escluso l''occhio\r','x11'),
('911','Traumatismo superficiale del tronco\r','x11'),
('912','Traumatismo superficiale della spalla e del braccio\r','x11'),
('913','Traumatismo superficiale del gomito, dell''avambraccio e del polso\r','x11'),
('914','Traumatismo superficiale della mano, escluse le dita da sole\r','x11'),
('915','Traumatismo superficiale delle dita della mano\r','x11'),
('916','Traumatismo superficiale dell''anca, della coscia, della gamba e della caviglia\r','x11'),
('917','Traumatismo superficiale del piede e delle dita del piede\r','x11'),
('918','Traumatismo superficiale dell''occhio e dei suoi annessi\r','x11'),
('919','Traumatismo superficiale di altre, multiple e non specificate sedi\r','x11'),
('920','Contusione della faccia, del cuoio capelluto e del collo escluso l''occhio\r','x12'),
('921','Contusione dell''occhio e dei suoi annessi\r','x12'),
('922','Contusione del tronco\r','x12'),
('923','Contusione dell''arto superiore\r','x12'),
('924','Contusione dell''arto inferiore e di altre e non specificate sedi\r','x12'),
('925','Schiacciamento della faccia, del cuoio capelluto e del collo\r','x13'),
('926','Schiacciamento del tronco\r','x13'),
('927','Schiacciamento dell''arto superiore\r','x13'),
('928','Schiacciamento dell''arto inferiore\r','x13'),
('929','Schiacciamento di sedi multiple e non specificate\r','x13'),
('930','Corpo estraneo nella parte esterna dell''occhio\r','x14'),
('931','Corpo estraneo nell''orecchio\r','x14'),
('932','Corpo estraneo nel naso\r','x14'),
('933','Corpo estraneo nella faringe e laringe\r','x14'),
('934','Corpo estraneo nella trachea, nei bronchi e nei polmoni\r','x14'),
('935','Corpo estraneo nella bocca, nell''esofago e nello stomaco\r','x14'),
('936','Corpo estraneo nell''intestino tenue e nel colon\r','x14'),
('937','Corpo estraneo nell''ano e nel retto\r','x14'),
('938','Corpo estraneo nell''apparato digerente, sede non specificata\r','x14'),
('939','Corpo estraneo nelle vie genitourinarie\r','x14'),
('940','Ustione limitata all''occhio e ai suoi annessi\r','x15'),
('941','Ustione della faccia, della testa e del collo\r','x15'),
('942','Ustione del tronco\r','x15'),
('943','Ustione dell''arto superiore, esclusi il polso e la mano\r','x15'),
('944','Ustioni del polso e della mano\r','x15'),
('945','Ustione dell''arto inferiore\r','x15'),
('946','Ustione di sedi multiple specificate\r','x15'),
('947','Ustione di organi interni\r','x15'),
('948','Ustioni classificate secondo l''estensione della superficie corporea interessata\r','x15'),
('949','Ustione non specificata\r','x15'),
('950','Traumatismo del nervo ottico e delle vie ottiche\r','x16'),
('951','Traumatismo di altri nervi cranici\r','x16'),
('952','Traumatismo del midollo spinale senza segni di lesione vertebrale\r','x16'),
('953','Traumatismo delle radici dei nervi e dei plessi rachidei\r','x16'),
('954','Traumatismo di altri nervi del tronco, esclusi i cingoli scapolare e pelvico\r','x16'),
('955','Traumatismo dei nervi periferici del cingolo scapolare e dell''arto superiore\r','x16'),
('956','Traumatismo dei nervi periferici del cingolo pelvico e dell''arto inferiore\r','x16'),
('957','Traumatismo di altri e non specificati nervi\r','x16'),
('958','Alcune complicazioni precoci di traumatismi\r','x17'),
('959','Altri e non specificati traumatismi\r','x17'),
('960','Avvelenamento da antibiotici\r','x18'),
('961','Avvelenamento da altri farmaci anti-infettivi\r','x18'),
('962','Avvelenamento da ormoni e sostitutivi sintetici\r','x18'),
('963','Avvelenamento da sostanze essenzialmente sistemiche\r','x18'),
('964','Avvelenamento da sostanze agenti principalmente sui costituenti del sangue\r','x18'),
('965','Avvelenamento da analgesici, antipiretici e antireumatici\r','x18'),
('966','Avvelenamento da anticonvulsivanti e da farmaci anti-parkinsonismo\r','x18'),
('967','Avvelenamento da sedativi e ipnotici\r','x18'),
('968','Avvelenamento da altri depressori del sistema nervoso centrale e anestetici\r','x18'),
('969','Avvelenamento da sostanze psicotrope\r','x18'),
('970','Avvelenamento da stimolanti del sistema nervoso centrale\r','x18'),
('971','Avvelenamento da farmaci agenti principalmente sul sistema nervoso autonomo\r','x18'),
('972','Avvelenamento da farmaci agenti principalmente sul sistema cardiovascolare\r','x18'),
('973','Avvelenamento da farmaci agenti principalmente sull''apparato gastrointestinale\r','x18'),
('974','Avvelenamento da farmaci agenti sul metabolismo dell''acqua, dei minerali e dell''acido urico\r','x18'),
('975','Avvelenamento da farmaci agenti principalmente sulla muscolatura liscia e striata e sull''apparato respiratorio\r','x18'),
('976','Avvelenamento da sostanze agenti principalmente sulla pelle e sulle mucose e da farmaci di uso in oftalmologia, otorinolaringoiatria e odontoiatria\r','x18'),
('977','Avvelenamento da altri e non specificati farmaci e medicamenti\r','x18'),
('978','Avvelenamento da vaccini batterici\r','x18'),
('979','Avvelenamento da altri vaccini e prodotti biologici\r','x18'),
('980','Effetti tossici dell''alcool\r','x19'),
('981','Effetti tossici dei derivati del petrolio\r','x19'),
('982','Effetti tossici di altri solventi derivati dal petrolio\r','x19'),
('983','Effetti tossici di sostanze corrosive aromatiche, acidi e alcali caustici\r','x19'),
('984','Effetti tossici del piombo e dei suoi composti (compresii vapori)\r','x19'),
('985','Effetti tossici di altri metalli\r','x19'),
('986','Effetti tossici dell''ossido di carbonio\r','x19'),
('987','Effetti tossici di altri gas, fumi o vapori\r','x19'),
('988','Effetti tossici di sostanze nocive ingerite come alimenti\r','x19'),
('989','Effetti tossici di altre sostanze di origine principalmente non medicamentosa\r','x19'),
('990','Effetti delle radiazioni, non specificati\r','x20'),
('991','Effetti del freddo\r','x20'),
('992','Effetti del calore e della luce\r','x20'),
('993','Effetti della pressione atmosferica\r','x20'),
('994','Effetti di altre cause esterne\r','x20'),
('995','Alcuni effetti avversi non classificati altrove\r','x20'),
('996','Complicazioni peculiari di alcuni interventi specificati\r','x21'),
('997','Altre complicazioni di protesi, impianti e innesti interni\r','x21'),
('998','Altre complicazioni di interventi, non classificati altrove\r','x21'),
('999','Complicazioni di cure mediche non classificate altrove\r','x21'),
('V01','Contatto con o esposizione a malattie trasmissibili\r','z1'),
('V02','Portatore o portatore sospetto di malattie infettive\r','z1'),
('V03','Necessita'' di vaccinazione contro malattie batteriche\r','z1'),
('V04','Necessita'' di vaccinazione e inoculazioni profilattiche contro alcune malattie virali\r','z1'),
('V05','Necessita'' di altra vaccinazione e inoculazioni profilattiche contro singole malattie\r','z1'),
('V06','Necessita'' di vaccinazione con vaccini combinati contro piu'' malattie\r','z1'),
('V07','Necessita'' di isolamento e di altre misure profilattiche\r','z2'),
('V08','Stato infettivo asintomatico da virus da immunodeficienza umana (HIV)\r','z2'),
('V09','Infezione da microrganismi resistenti ai farmaci\r','z2'),
('V10','Anamnesi personale di tumore maligno\r','z3'),
('V11','Anamnesi personale di disturbo psichico\r','z3'),
('V12','Anamnesi personale di alcune altre malattie\r','z3'),
('V13','Anamnesi personale di altre malattie\r','z3'),
('V14','Anamnesi personale di allergia a sostanze medicinali\r','z3'),
('V15','Altra anamnesi personale con rischio di malattia\r','z3'),
('V16','Anamnesi familiare di tumore maligno\r','z3'),
('V17','Anamnesi familiare di alcune malattie croniche invalidanti\r','z3'),
('V18','Anamnesi familiare di alcune altre manifestazioni morbose definite\r','z3'),
('V19','Anamnesi familiare di altre manifestazioni morbose\r','z3'),
('V20','Controllo della salute del neonato o del bambino\r','z4'),
('V21','Stati costituzionali dello sviluppo\r','z4'),
('V22','Gravidanza normale\r','z4'),
('V23','Controllo di gravidanza ad alto rischio\r','z4'),
('V24','Cure ed esami postpartum\r','z4'),
('V25','Misure contraccettive\r','z4'),
('V26','Misure procreative\r','z4'),
('V27','Esito del parto\r','z4'),
('V28','Ricerche nella donna per lo screening prenatale\r','z4'),
('V29','Osservazione e valutazione di neonati per sospetto di manifestazioni morbose non riscontrate\r','z4'),
('V30','Nato singolo\r','z5'),
('V31','Gemello di gemello nato vivo\r','z5'),
('V32','Gemello di gemello nato morto\r','z5'),
('V33','Gemello non specificato se di gemello nato vivo o morto\r','z5'),
('V34','Altro parto multiplo (tre o piu'' ), tutti nati vivi\r','z5'),
('V35','Altro parto multiplo (tre o piu'' ), tutti nati morti\r','z5'),
('V36','Altro parto multiplo (tre o piu'' ), alcuni nati vivi e altri nati morti\r','z5'),
('V37','Altro parto multiplo (tre o piu'' ), non specificato se di gemelli nati vivi o morti\r','z5'),
('V39','Nato vivo, non specificato se singolo o gemello di uno o di piu'' gemelli\r','z5'),
('V40','Problemi psichici e di comportamento\r','z6'),
('V41','Problemi degli organi dei sensi e di altre funzioni speciali\r','z6'),
('V42','Organo o tessuto sostituito da trapianto\r','z6'),
('V43','Organo o tessuto sostituito con altri mezzi\r','z6'),
('V44','Presenza di aperture artificiali\r','z6'),
('V45','Altre Patologie successive a interventi chirurgici o procedure\r','z6'),
('V46','Dipendenza da apparecchiature meccaniche\r','z6'),
('V47','Altri problemi degli organi interni\r','z6'),
('V48','Problemi relativi alla testa, al collo e al tronco\r','z6'),
('V49','Problemi relativi agli arti e altri problemi\r','z6'),
('V50','Interventi chirurgici senza ragioni mediche\r','z7'),
('V51','Trattamento dopo intervento che richiede l''impiego di chirurgia plastica\r','z7'),
('V52','Collocazione e sistemazione di protesi\r','z7'),
('V53','Collocazione e sistemazione di altri dispositivi\r','z7'),
('V54','Altro trattamento ortopedico ulteriore\r','z7'),
('V55','Controllo di aperture artificiali\r','z7'),
('V56','Trattamento ulteriore che richiede dialisi intermittente\r','z7'),
('V57','Cure riabilitative\r','z7'),
('V58','Altri e non specificati procedimenti e trattamenti ulteriori\r','z7'),
('V59','Donatori\r','z7'),
('V60','Abitazione, problemi familiari ed economici\r','z8'),
('V61','Altri problemi familiari\r','z8'),
('V62','Altri problemi psicosociali\r','z8'),
('V63','Indisponibilita'' di altri servizi medici\r','z8'),
('V64','Persone che ricorrono ai servizi sanitari per interventi specifici non eseguiti\r','z8'),
('V65','Altre persone che entrano in contatto con i servizi sanitari\r','z8'),
('V66','Convalescenza e cure palliative\r','z8'),
('V67','Visita di controllo e di follow up\r','z8'),
('V68','Contatti per scopi amministrativi\r','z8'),
('V69','Problemi legati allo stile di vita\r','z8'),
('V70','Esame medico generale\r','z9'),
('V71','Osservazione e valutazione per sospetto di manifestazioni morbose\r','z9'),
('V72','Visite ed esami speciali\r','z9'),
('V73','Esame speciale per l''individuazione di malattie virali e da Chlamidie\r','z9'),
('V74','Esame speciale per l''individuazione di malattie batteriche e da Spirochete\r','z9'),
('V75','Esame speciale per l''individuazione di altre malattie infettive\r','z9'),
('V76','Esame speciale (screening) per l''individuazione di tumori maligni\r','z9'),
('V77','Screening per l''individuazione di disturbi endocrini, nutritivi, metabolici e immunitari\r','z9'),
('V78','Screening per l''individuazione di disturbi del sangue e degli organi ematopoietici\r','z9'),
('V79','Screening per l''individuazione di disturbi psichici e difetti dello sviluppo\r','z9'),
('V80','Screening per l''individuazione di malattie neurologiche, dell''occhio e dell''orecchio\r','z9'),
('V81','Screening per l''individuazione di malattie cardiovascolari, respiratorie e genitourinarie\r','z9'),
('V82','Screening per l''individuazione di altre manifestazioni morbose\r','z9'),
('V83','Portatore di malattia genetica\r','z10'),
('V84','Suscettibilita'' genetica alle malattie\r','z10'),
('V85','Indice di massa corporea [BMI]\r','z11'),
('V86','Stato dei recettori degli estrogeni\r','z12'),
('Y01','Altro\r','y1');